---
---
---

# Judy Cheats at Bingo

> *Nickel Bingo Every Thursday Night at 6:00 p.m.*

There are two notable things wrapped up in this sentence. Least of the two, but still significant, is the time: activities here at Dimensions Living occuring past 5:00 are considered late-evening. ~~Dinner~~ Supper is served from 4:30 to 5:30; past then the halls become the turf of the night owls. Gatherings are secretive.

Previous to Dimensions Living, these late-night residents would have huddled around the corner table in a seedy bar, speaking in lowered voices and pausing their negotiations when the waitress comes by to refill drinks. Six O'clock is when the sharks circle the waters of Dimensions Living.

On Thursday evenings, the sharks swim to the Independent Dining Room (aka IDR) for nickle bingo. This crowd has unofficially agreed on assigned seating, although there was an official memo to the contrary. I advise visitors to sit at a table in the periphery of the room to avoid crashing the normal order; even then, you may find yourself crowding in as the fifth at a table of four. Maybe you should consider just watching, rather than disrupting the clean geometry of two bingo cards per side of the table.

Nickel Bingo is the second of notable things this evening. Yes, there are other bingo games during the week. But I will point out candy bingo and jewelry bingo are minor-league to nickle bingo. The Dimensions Living bingo sharks occasionally appear at these events, but only to toy with those residents less dedicated to the game. If you win at candy or jewelry bingo, you get to choose a piece of candy (or a piece of jewelry). But, *you don't have to put anything in the cup to play*. For these lessor games, you can show up empty-handed and still win. Not so with nickle bingo.

I have asked the activities coordinators if there is ever gun bingo, fishing lure bingo, or whiskey bingo. I'd like to organize an underground bingo association for the men, and the poorly-lit basement parking garage would be ideal for a cigar-smoking, whiskey-drinking, Friday night game. So far, I have abstained from instigating. I don't want to be the cause (or subject) of an official memo on appropriate evening activities.

It's essential to understand the game of bingo if you hope to understand the drama associated with nickle bingo. Simply explained, each player in the room possesses a bingo card with a matrix of random numbers. The caller sits in front and announces a series random numbers. When a called number matches a number on the player card, the player marks this position. When the marked positions on a bingo card align in a pattern (such as a complete row or column) the player calls out "BINGO." Assuming all the player numbers match caller numbers, the player is a winner. Everyone calls out in amazement and the game is reset. In a minute I will introduce considerations that often result in mayhem.

Random numbers are traditionally generated with a bucket of numbered balls, although impure heathens resort to computer programs. With the bucket-of-balls approach used at Dimensions Living, the caller retrieves a ball, then reads the printed value. Again, there are nuances which result in further mayhem.

Until I did research for this article, I did not understand there are different types of bingo. The number of balls used to generate random numbers can vary from thirty to ninety. The rows and columns on the cards, when multiplied, can equal as few as nine positions and as many as twenty-five. Here at Dimensions Living, we play american bingo; seventy-five balls for random number generation and the players use cards with a five-by-five matrix of integers. Each column is topped by the letters of "BINGO." The center square is marked as "FREE." I don't believe you are allowed to bring your own card, although I haven't tried. At the least, it would be a topic of conversation for weeks and might even be the cause of another memo.

Our bingo cards are environmentally-friendly; each number appears in a window with a sliding, transparent-red piece of plastic. When a number is called, you slide the plastic down. When the game is over, you slide the plastic to the top of each window and prepare for the next round.

To play nickle bingo, you'll need a jar of nickles. Quarters, dimes, pennies, and even dollar bills will suffice, but, as you will see, non-nickles cause unnecessary confusion. For god sake, don't bring foreign currency.

Picture yourself seated at a table with three friends. In front of each of you are two bingo cards. (You could play more, but two seems to be the accepted norm. And I strongly advise you to stick to the accepted norm).

In the middle of the table is a finger bowl. It might be empty or it might contain change. If you want to play this round of bingo (and you do, or you wouldn't be sitting at this table) you must contribute one nickle per bingo card. Two bingo cards, two nickles. Four people at the table times two bingo cards will result in eight nickles in the bowl. Which equals forty cents. Instead of two nickles, you are allowed to deposit one dime. If you deposit a quarter, you can remove fifteen cents from the bowl.

Before each round of bingo can begin, the designated money collector gathers the contents of each bowl. It's assumed the money collector confirms each table has contributed the correct amount. This collection is then placed at the head table and the bingo caller can proceed.

Not so fast...

It would seem this task is inconsequential, but it is not. First, being asked to perform this job is an honor. An informal and self-designated sub-committee of bingo sharks bestows this honor. The qualifications are not available for public review anywhere that I've seen, but I believe the ability to squeeze between the tightly-packed tables is an essential skill. This requires the ability to bend your knees and locomote without the assistance of a walker or wheelchair. I am proud to note I have been asked to perform this task and discharge my duties with the earnestness of first-time student council president.

The task of collecting bingo fees must be done with efficiency; the game is, after all, delayed until this task is completed. We are waiting, but not patiently. Pick up the bowl, count the change. That should be simple enough.

However. What is the proper response if the value is not correct?

Your first strategy might be to ask if everyone has contributed their two nickles. If you're fortunate, one member of the table will realize it is time to ante-up and contribute their fair share. Unfortunately, this often does not happen.

Two other things may have happened. This table may be assuming that nickles are placed in the cup *after* the money collector has emptied the bowl for the current round. This is an advanced bingo shark technique done in preparation for the next round. Speaking from personal experience, it is easy to become confused about the state of the bowl and you would be mistaken to blame this on any of the seven stages of dementia.

Since you, the collector, are an outsider to the table, you do not have visibility into the intent of the table. You will be unable to audit the flow of cash into the bowl. Your only hope is intervention from one of the table members. Or you can do as I do and just agree everything is accurate, then pour this bowl into the general collection.

The other possible event is a change-making anomaly, usually indicated by the presence of a quarter in the bowl and exacerbated by the cumulative arthritis of everyone at the table. Nickles are difficult to pick up when your knuckles are grinding bone-on-bone. To develop empathy, I suggest you insert 60-grit sandpaper between each joint in your fingers so it is excruciating to flex them, then wrap each finger in duct-tape so you are unable to flex. Now pick up three nickles placed in a small bowl to make change for your quarter. As above, I choose to agree everything is accurate and move on to the next table. I'm very popular.

During your training to become certified as a bingo money collector, you'll also learn of the inadvertent bowl collection confusion. Here's a scenario:

1.  Arrive at the table. Develop empathy with the sharks at this table. Assure them they will win during this round.

2.  Someone will need change, most likely for a dollar. Happily count out nickles from the bingo fees you've already collected. Exchange those nickles for the dollar.

3.  Move to collect the bowl from the table. In some cases, someone will object; "You've already collected for this round."

You may think you are certain you have not collected. But you are only one vote out of five, the other four being the players seated at the table. They may be assuming the bowl contains money for the next round. The act of making change may have interrupted the normal flow of the interaction between sharks and collectors. Or sadly, there may be some dementia and short-term memory is a bit wobbly.

You might choose to reason through a narrative of the collection. Again, you are one vote out of five. I believe the correct answer is to move on. After all, it's only forty cents.

At times, someone may be unable to contribute or is somehow flustered with the quick flow of money across the table. I've learned to carry a supplemental pocket of nickles and make a lightning loan where necessary. "I've got you covered," I tell my new friend. Everyone usually forgets about the loan, but the friendship remains.

STUFF

(RESIDENT LEAD - These are suggested activities that residents can choose to participate in and are either lead by a resident or done on your own. )

At times when I am less engaged, my mind wanders through the wonderful math of the game. I teach a statistical programming language called, simply, "R." There are algorithmic rules for the placement of numbers on the board. Each column has a range of discrete integers, each integer can only appear once, the integers must be random in value and occurrence.

I shared this with Janell and she gave me a look I have received only once before. I had excitedly discussed my progress on creating an etch-a-sketch program for the Apple IIe computer, written in assembler. At the time, we were dirt-poor and she failed to see how this could be a career-enhancing pursuit.

As much as I would like to inflict a comprehensive discussion of the programming necessary to generate the bingo matrix, I realize the audience for this sort of thing is limited. Instead, I have added an appendix with code to create a proper bingo card. You're welcome.

## Appendix

Here is R code to build an american bingo card...

```{r}
gimmeFive <- function(range) {
  as.character(sample(x = range, size = 5))
}

BingoMatrix <- matrix(data = c(gimmeFive(1:15),
                               gimmeFive(16:30),
                               gimmeFive(31:45),
                               gimmeFive(46:60),
                               gimmeFive(61:75)),
                      nrow = 5)

colnames(BingoMatrix) <- c("B","I","N","G","O")

BingoMatrix[3,3] <- "Free"

BingoMatrix
```
