---
title: "Nickel Bingo"
author: "Mark Niemann-Ross"
format: docx
editor: visual
---

## A New Home

At 63 years old, I'm the youngest member of my Mother-In-Law's senior residence hall. How this happened is an interesting story, but one for later. It's enough to know I'm helping her recover her strength and that requires my presence 24x7. Unexpectedly, I have access to a wealth of new perspectives from an older generation.

This is the generation who told me I needed a haircut, who told me Satan inspired the Beatles, and who told me astronauts drank Tang. It's also the generation that changed my diapers, let me use the family car, and currently occupies the highest seats of government.

Every Sunday, a weekly activity guide appears in my mailbox. Fitness Class is Monday at 1:00 p.m. The Catholics among us recite The Rosary at 2:30 on Wednesdays. Ice Cream is just before the Rosary. Pub night is Thursday evening at 6:00.

That's all very nice, but how we *long* for bingo night.

## Two Important Things

*Nickel Bingo is every Thursday night at 6:00 p.m.*

There are two notable things about this sentence. Least of the two, but still significant, is the time: Nickel Bingo happens at 6 p.m. Activities occurring past 5:00 p.m. are *late-evening*. ~~Supper~~ ~~Dinner~~ Supper is served from 4:30 to 5:30 p.m.; past then, the halls become the domain of the night owls. Any resident gatherings after six p.m. feel surreptitious. Walk unannounced into one of the activity rooms and you may find residents quietly playing Rummikub, but that's just to avert suspicion; when you move out of earshot, they will return to plotting world domination.

Previous to living here, these late-night residents would have huddled around the corner table in a seedy bar, speaking in lowered voices and pausing their negotiations when the server came by to refill drinks. After living here for a month, they trust me a bit. But they still change conversation when I approach.

At six o'clock, the sharks circle the silent waters of my residence hall. At six o'clock on Thursday evenings, the sharks forego Rummikub and swim to the Independent Dining Room for *nickel bingo*.

## Nickel Bingo

Nickel Bingo is the second of notable things in the above sentence. There are *other* bingo games during the week, notably candy bingo and jewelry bingo, but these are minor-league compared to nickel bingo. If you win at candy or jewelry bingo, you get to choose a piece of candy (or a piece of jewelry). But, *you don't have to put anything in the cup to play*. For these games, you can show up empty-handed and still win. The bingo sharks take part in these lesser events, but only as a side to the big event on Thursday evening.

Very few men take part in candy or jewelry bingo. I have asked the activity coordinators if there is ever gun bingo, fishing lure bingo, or whiskey bingo. (answer: *no!*) I've thought of organizing an underground bingo association for the men; the poorly lit basement would be ideal for a cigar-smoking, whiskey-drinking, Friday night game. So far, I have abstained from instigating this clandestine event. I don't want to be the cause (or subject) of an *official memo* on appropriate evening activities.

::: {.callout-note icon="false"}
## Official Memos

Official memos come from the Facility Director. They are copied on letterhead and appear in your campus mail slot; sometimes posted in the elevator. The instigating resident or precipitating situation is only vaguely insinuated, but the intent is clear: *"Keep it up, buster, and your children will be interviewing other residence halls for your next placement."*
:::

## Bingo Basics

Knowing the essentials of bingo will help you understand the drama associated with nickel bingo. I'll make this as brief as possible, after which I'll explain why our bingo night frequently descends into mayhem.

Simply explained, each bingo player possesses one or more printed cards displaying a grid of random numbers. The bingo caller sits in front of the room and announces another series of random numbers. When a called number matches a number on the player card, the player marks this position on the grid. When the marked positions on a bingo card align in a pattern (such as a complete row or column) the player calls out "BINGO." Assuming all the player numbers match caller numbers, the player is a winner. Everyone calls out in amazement and the game is reset.

The random numbers are traditionally generated with a bucket of numbered balls, although some callers use a computer. With the bucket-of-balls approach, the caller shuffles the balls (either by hand in a bucket or with a tumbler cage), retrieves a ball, then reads the value printed on the ball. Computer applications select a random number at the push of a button, then display it on screen. Computers are more efficient, but lack the aesthetics of numbered balls.

Until recently, I did not understand there are different versions of bingo depending on where you live. The number of balls used to generate random numbers can vary from thirty to ninety. The rows and columns on the cards can be anywhere from three by three to five by five. At our residence hall, we play American bingo; seventy-five balls are used for random number generation and the players use cards with a five-by-five grid. The letters of "BINGO" top each column. The center square is marked as "FREE."

If you want to play, you select a bingo card from a stack on the middle table. I don't believe you can bring your own card, although I haven't tried. This isn't like pool where you bring your custom-made stick. Private bingo cards, at the least, would be a topic of conversation for weeks; at worst, it would be the topic of another *official memo*.

Our bingo cards are reusable; each number appears in a window with a sliding, transparent-red piece of plastic. When a called number matches a number on your card, you slide the plastic over the number. When someone wins, you slide the plastic to the top of each window and prepare for the next round. With age, these plastic sliders become sticky and difficult to move. I have found no maintenance instructions. I've tried to disassemble a card for better access to the internals, but like carburetors and mobile phones, I don't have the proprietary bingo card tool and my many attempts have only resulted in fewer operational cards.

When I am less engaged in the game, my mind wanders through the wonderful math of these cards. The numbers are random, but within a range for each column. I once shared this observation with my wife and she gave me a look I have received only once before. In that case, I had excitedly discussed my progress in creating an etch-a-sketch program for the Apple //e computer, written in assembler. We were dirt-poor and she failed to see how this could be a career-enhancing pursuit. (Side note: It *was* career enhancing, but that's another story.)

## The Player Table

Our bingo sharks have unofficially agreed on assigned seating, although this was discouraged by an *official memo*. Visitors might consider sitting at a table on the room's periphery to avoid crashing this unspoken tradition. If you can't find a seat, maybe you should consider just watching, rather than causing a disruption. I have earned the position of honored guest and am invited to join one of the regular tables. 

Each of player has two bingo cards. (I could play more, but two seems to be the norm. And I've learned to stick to the norm. Mostly. Occasionally. *It's complicated*.)

If I forget to bring my jar of nickels, I will sponge off my Mother-in-law. She's gracious, but I worry this will strain our relationship. Her jar contains quarters, dimes, pennies, and sometimes dollar bills. I'll explain in a minute, but non-nickels cause confusion. For God's sake, don't bring foreign currency: This would be probable cause for yet another *official memo*.

A small bowl is in the middle of our table. It might be empty or it might contain change. At the beginning of each round we contribute one nickel per bingo card, placing the coins in the cup. Two bingo cards, two nickels. This is why we call this game nickel bingo. Four people at the table times two bingo cards results in eight nickels in the bowl. Which equals forty cents. Instead of two nickels, we are allowed to deposit one dime. If someone deposits a quarter, they can remove fifteen cents from the bowl.

Before I remove money from the bowl, I am *inordinately* clear about my action and intention. Someone might misconstrue sudden movement. Fortunately, weapons are not allowed in our building. But I don't want to be shunned. 

## Game Phase One-The Collection

Before each round of bingo can begin, the designated money collector circulates among the tables and gathers the coins from each bowl. We assume the money collector confirms each table has contributed the correct amount (*but maybe not. More on this in a minute*). This collection is placed at the head table and the bingo caller can proceed.

Collecting bingo fees must be done with efficiency. The sharks wait for the game to begin, but not patiently. Pick up the bowl, count the change. This should be simple enough.

*But not so fast...*

You might think the job of money collection is inconsequential, but it is not. An informal and self-designated sub-committee of bingo sharks bestows the honor of money collector upon an individual. The qualifications are not available for public review anywhere that I've seen, but I believe the main qualifier is squeezing between tightly packed tables, walkers, and wheelchairs. This requires the ability to bend your knees and locomote without support. I am proud to note I have been asked to perform this task and have discharged my duties with the earnestness of a first-time student council president.

Now--I propose a conundrum for you to consider. *What is the proper response if the change is not correct for the number of bingo cards visible on the table?*

The obvious strategy would be to ask if everyone has contributed. When I'm fortunate, one member of the table will realize it is time to ante-up and contribute their fair share. Unfortunately, this rarely happens.

There are two complexities to consider, possibly more. For example, this table may assume that nickels are placed in the cup *after* the money collector has emptied the bowl for the current round. This is an advanced bingo shark technique. Speaking from personal experience, it is easy to become confused about the state of the bowl and you would be mistaken to blame this on any of the seven stages of dementia.

It's also possible there is a change-making anomaly, one indicator being the presence of a quarter in the bowl and exacerbated by the cumulative arthritis of everyone at the table. Arthritis is when your knuckles grind bone-on-bone. To develop empathy, insert 60-grit sandpaper between each joint in your fingers so it is excruciating to bend them, then wrap each finger in duct-tape so you cannot flex. Now pick up three nickels placed in a small bowl to make change for your quarter.

In all cases, I've found it easiest to just agree everything is accurate, then pour this bowl into the general collection. This isn't an IRS audit and the amount to be won is secondary to the win itself. Smile and move on.

During my training to become certified as a bingo money collector, I also learned of the inadvertent bowl collection confusion. Here's a scenario:

1.  I arrive at the table and develop empathy with the sharks. I assure them they will win during this round. They assume I am lying to gain their favor, which is true.

2.  Someone will need change, most likely for a dollar. I count out nickels from the bingo fees I've already collected, then exchange those nickels for the dollar.

3.  I reach to collect the bowl from the table. In this scenario someone will object; "You've already collected for this round."

I may think I am *certain* I have not collected. But I am only one vote out of five, the other four being the players seated at the table. They may assume the bowl contains money for the next round. The act of making change may have interrupted the normal flow of the interaction between sharks and collector. Or sadly, shark short-term memory is a bit wobbly. Untangling this error in cash flow is tortuous. I've tried to reason through a narrative of the collection, but the accounting trail is obscured. Again--smile. Move on.

At times, someone may be unable to contribute or is flustered with the quick flow of money across the table. I've learned to carry a supplemental pocket of nickels and make a lightning loan where necessary. *"I've got you covered,"* I tell my new friend. In a few minutes everyone forgets about the loan, but the friendship remains. I count that as a win.

As you might realize, collections became an issue of major contention and even made it to a topic of discussion at a town hall. Two volunteers stepped up with a plan; now we have a collection system inspired by the traditions of the Lutheran Church.

## Game Phase Two-The Calling

After money is collected, the bingo caller proceeds with the announcement of the numbers. Again, let me explain the simple concept, then I'll explain the nuances that lead to shouting.

::: {.callout-note icon="false"}
## Bingo Caller Certification

You might think I am kidding about bingo caller certification. I am not. Depending on location, you may be required to take a class, pass a test, and/or annually renew your license. Search the internet for *bingo certification* for details.
:::

To start, the caller withdraws one ball from a bucket of 75 and announces the letter/number combination ("G-48. That's GEE...FOUR...EIGHT), then--and this is important--places the ball in the correct place in a master matrix with seventy-five depressions. Each hole is numbered and arranged in five columns of fifteen rows. Each column is labeled with one letter from the word "BINGO." With the ball safely in place, the caller repeats the process. The master matrix is an easy way to confirm which numbers have been called. Which is really important when someone calls...

**BINGO!**

### What could possibly go wrong?

Before we get to the climax of the evening, I'll discuss the reality of a live bingo game in the context of a simplified communication model. There are many models proposed by communications experts; I'll just consider the sender, noise, and the receiver.

#### Sender

Qualities of a good bingo caller--the sender, in this discussion--include enunciation, volume, and pacing. This is much like an auctioneer, but slower. There is such a thing as lightning bingo--but not here.

Ideally, the bingo caller will draw a ball from the bucket, then pause to look at the letter/number on the ball, call out the number clearly and carefully, pause, repeat the letter/number, place the ball in the master matrix, pause, shuffle the balls, and draw the next ball.

However, some callers have forgotten their training and acquire bad habits: Speaking softly. Sloppy pronunciation. Calling too fast. When auditioning a caller, we favor experience as pastor, square-dance caller, sports announcer, elementary school teacher, or game-show host. Unfortunately, the qualification of the caller is not the only chaotic force in action.

Pacing is every bit as important as volume and enunciation. As we age, our brains suffer a reduction in processing speed. When I was twenty-years-old, I could do advanced math in my head. I could also perform deep-knee bends while lifting seventy-pound weights. Forty years later, math takes longer and my knees support less weight. Pausing between bingo calls gives everyone a chance to hear the number, parse the number, check both bingo cards, slide the plastic cover on a number, wiggle the cover if it sticks, confirm the number with a neighbor, check for a bingo pattern, and re-focus in preparation for the next number.

To develop empathy, imagine a professor calling out polynomial equations at the pace of one per minute. I might solve the first one. Possibly the second. By the third I would call for a pause, and by the fourth I would be irretrievably lost and complaining to my table-mates. Madness and shouting would ensue. The sharks don't like it when bingo callers move too fast.

#### Noise

Communication models include the channel of transmission (paper for writing, copper wires for phone calls, air for sound) and include noise as a complicating factor. Smeared ink for paper, static for phone calls, and rattling bingo balls for bingo callers.

About those damn bingo balls. They are plastic; every time the caller stirs the bucket of balls, they generate noise akin to a ball-bearing factory. It masks human speech. The bingo sharks tell callers not to stir the balls while calling a number. If they don't pause long enough between calling the number and stirring the balls, we hear the following...

> "O-63...that's O- (RATTLERATTLERATTLE). The next number is B-3. That's B- (RATTLERATTLERATTLE)."

RATTLERATTLERATTLE causes a cascade of secondary noise, caused by one or more calls to repeat the last number, followed by 25% of the bingo players repeating the number (out of sync, so the response is also confused) followed by the bingo caller demanding silence, which is followed by another 25% of bingo players again asserting the latest number simultaneous to a different 25% asking if it was a different number, followed by the caller repeating the number, followed by someone asking if that is the last number or the next number. simultaneously, there is background rumbling about the caller being inaudible or the players needing to pay better attention. I suspect this is the reason we cannot keep bingo callers for more than a couple of months.

Also problematic is outsiders: relatives, children, nursing staff, janitors. Relatives and children are the worst, as they have no respect for the sanctity of the game in progress. Typically, they appear at the door of the bingo parlor, squeal, and call out; "GRANDMA! WE'RE HERE!" They invade our bingo sanctuary en masse, surround their relative and talk loudly about their *car trip* and *how good it is to see them* and *how big the kids have grown* and *we have this pie we baked for you* and *what's going on here* and *Oh, I love bingo* and *we should join in*.

I'm enthusiastic about visitors. They brighten up everyone's day. But *gawdammit*, we're trying to play **bingo** here. ***Nickel Bingo!***

Likewise, the nursing staff will sometimes stop by for blood pressure and pulseOx. They truely are heroes and wrangle medications with grace and care. But the brief interruption in game play means possibly missed numbers, causing one or more calls to repeat the last number, followed by 25% of the bingo players repeating the number ... and so on.

If maintenance is working late, they may vacuum in the next room. A vacuum cleaner produces something called "white noise," and it masks the bingo caller's voice. Players won't be able to hear, one or more calls to repeat the last number ... and further so on and so forth.

#### Receiver

If the caller enunciates, projects, and paces--and someone's kid isn't playing with a vacuum cleaner or banging out chopsticks on the piano, then it is reasonable to assume everything will go smoothly. However, there is still the matter of the receiver. The bingo player in this scenario.

By age 80, it's not uncommon to have a hearing loss of 50% in the frequency range of the human voice. Roughly one-third of the bingo players have some level of dementia, one symptom being confusion and agitation when dealing with the cacophony of many people talking at once. My friends are doing their best, but they need a bit of slack.

Do you wonder how this feels? Try balancing your checkbook while teaching a first-year band class. Add in a persistent five-year-old learning to tie their own shoes. This is an example of cacophony as applied to bingo. Formally this is known as cognitive overload. Informally this is *Can you all just be quiet for just five minutes oh my gawd I'm getting a headache!*

By the way, good table mates look out for each other. After I scan my bingo cards, I stealthily scan my neighbor's cards and politely point out any numbers they may have missed. Done quietly, this is a gesture of kindness.

## Game Phase Three-BINGO

**BINGO!**

It eventually happens. Sometimes from another table. Sometimes from my table. Sometimes I double-take at my card, realize I have the game pattern and hear myself yell **BINGO**.

In American bingo, there are three basic winning patterns: Five in a row, five in a column, and five diagonally. We have three additional patterns: four corners, picture frame, and the high-stakes *blackout*. (more about blackout in a minute) Some callers try additional patterns (i.e. postage stamp, two lines, small diamond) but approval among the sharks is mixed.

Upon hearing bingo, the caller pauses the game and performs verification of the winner.

An experienced caller will remind players *not* to clear their board in case this bingo isn't confirmed. An inexperienced caller will forget this step and players will clear their boards. If a bingo is not confirmed, the confusion quotient of the room will rise. A player whom mistakenly cleared their board will request a re-call of all the drawn numbers, but that takes time and is not a popular suggestion. By the way, not clearing your bingo card until confirmation is an earmark of an experienced player. If you wait until confirmation, congratulations, you are on your way to bingo sharkdom.

Confirming a bingo is mechanically easy, but can be problematic. If everything runs smoothly, the winning player reads out-loud the numbers comprising their bingo, the caller confirms those numbers were actually called and if in agreement, the caller confirms a winning bingo. To the winner goes the nickels and everyone resets their bingo cards.

Sometimes it isn't smooth. As in all steps of bingo, problems appear during the implementation. The concept of "out loud" has various interpretations with multiple variables, including speed of delivery and volume of the player. 

Here's a scenario: When I claim bingo, I carefully call out the five winning numbers, pausing and enuciating. For example, *8-16-Free-57-72*. "Free" because this is the middle row. I might include the corresponding B-I-N-G-O letters; *B8-I16-Free-G57-O72*.

But...maybe the caller's hearing isn't as good as it used to be. Maybe other players are chatting/gossiping/remarking at how close *they* were at winning. Maybe the caller's memory for numbers isn't 100%.

Confirming a bingo often takes multiple tries. But in the end (usually) everything works out and we have a winner.

### Blackout Bingo

Each evening bingo session includes ten rounds with the standard row/column/diagonal bingo pattern. As mentioned above, these games cost one nickel per card. There is an additional, final round which uses a blackout pattern--cover **all** windows on the card. It surprised me to learn the cost per card doubles to *ten cents per card*. The table ante doubles from fourty cents to eighty cents. Our bingo room has space for seven tables, so winning blackout bingo is a big payout--over FIVE DOLLARS!

Blackout bingo takes longer than standard patterns, but the suspense is *killer!* I feel my blood pressure rise as I watch the card approach 100% coverage. Several times I've had only two, maybe one window open. Several times my fantasy of a big payout has been crushed by someone else calling **BINGO**. *Dammit!*

## Game Phase Four-PAYOUT

I've won several times! Each time I was tempted to do a victory dance, beat my chest, throw my winning bingo card across the room and shout "**I DOMINATE! I AM THE BINGO JEDI MASTER! COWER IN FEAR, ALL WHO BEHOLD ME!**"

I haven't done this. My knees are not up to dancing around. My older table mates would be ill-advised to beat their chests, considering any history of heart trouble. Finally, throwing anything across the room is likely to poke someone's eye out. Surely this will result in an official memo.

When I win, I revel in the momentary endorphin rush of seeing a pile of change pour into my bingo change jar, I tell my table friends how much fun that was and how surprised I am to have won. Then I get ready for the next round.

### Two or More Winners

Normally, one single person wins each round, but it's not uncommon for two (or more) people to win simultaneously. (The odds of winning bingo is a fascinating subject if you are a statistician or math professor. Look it up on the internet. The rest of us should leave the math geeks in peace).

When multiple **BINGO!**s are confirmed, winners split the prize. As a money collector, it is my job to perform this split. There are three strategies I've used to accomplish this accounting feat of daring-do.

-   Total the money, then divide by the number of winners. Count out a pile for each winner.

-   Drag into piles. One for you. One for me. Repeat until all coins are distributed.

-   Eyeball. Hmm...this pile looks about this big. Some for one winner and some for the other winner.

There's a secret I learned and I'll tell you if you promise not to make a big damn deal about it.

Here's the secret: Where I live, *Nobody cares!*

I divide up the money in mostly equal piles, then give it to the winners. I pour that money into the winner's pouch or jar already containing an uncounted amount of change; there is no accounting trail or software involved. The thrill of the win counts. Delaying the start of the next game is a buzz kill.

## Cheating at bingo

We're pretty sure James cheats. He wins *a lot*--at least, more than he should. I think I've figured out how he does it. James sits with his back to a wall so no one can look over his shoulder. He uses small picture easels to hold his two bingo cards upright. In his mind, he combines these two cards into one, doubling his chances of a matching number. When he calls bingo and reads back his numbers, he may be reading the first number from the first card, then the second number from the *second* card, the third number from first (or second) card, and so-on.

I have two considerations about this. First, James is demonstrating advanced math skills by converting an exercise in random-number correlation from a two-dimensional matrix to a three-dimensional array. That's impressive stuff and I'm loath to call him on his adept transformations.

Second, James may not realize he's cheating. Our brains are masters of rerouting around faulty circuits. What we call cheating may actually be the result of an adaptation to a brain injury sustained on a Naval destroyer or Army tank. 

Either way, I gain nothing by destroying the elated mood surrounding an evening of nickel bingo.   

## Final Thoughts

My family played cards. The intent was to give your hands something to do while you talked. Games were a second act after family meals; we enjoyed hanging out together (most of the time) and we needed some sort of excuse to do so.

I play bingo with my friends. Some of them are losing their memory and reasoning and physical dexterity. All of them are getting older. The best part of playing bingo is hanging out with each other during the short time we have.
