---
title: "The Candy Basket"
author: "Mark Niemann-Ross"
format: docx
editor: visual
---

## Seven Hallways

There are seven hallways in the residence where I live; three are in the assisted living wing, three are in the independent wing, and one is in the memory wing. Each hallway services six or more rooms. Each room has a door with a small cubby to the side. It's a blank space that invites personal expression by the occupant of the room. Most cubbies have pictures of Jesus or Mary. Many have ceramic dogs or cats (but not both). There are plants and flags and war memorabilia and ceramic figures and wind chimes and drawings by grandchildren.

A few have artwork created by the occupant; our neighbor Jan paints mandala patterns on rocks. I will forever regret not introducing myself to Dave Smith, an art professor and member of my community. He dabbled in an abstract type of art he described as *Scarabocchio* - Italian for *scribble*. His door was a wild display of politics, opinions, and his multi-colored artwork. His door screamed I AM ECCENTRIC, I AM PROUD OF IT, IT IS WHO I AM. When you are in Stevens Point, Wisconsin, you can visit his museum.

I have not seen any lawn flamingos, neon beer signs, dancing hula girls, gum ball machines, coin-operated video games, or historical plaques.

A few cubbies host bird houses. There are no birds flying loose in our building and so the bird houses are empty. But do not underestimate the resourcefulness of my fellow residents. The excursion bus makes a weekly trip to a shopping mall. The mall contains a pet store. The pet store contains birds. Hmmm...

For our cubby, I considered an inflatable flappy-arm guy like you see at tire and furniture stores. At 20 feet tall, this would crowd against the eight-foot ceiling, plus the one-horsepower fan might generate more noise than my neighbors will tolerate. Instead, I may purchase a target-practice deer with replaceable core. I can purchase this at Fleet Farm across the street.

Until I act otherwise, our cubby hosts a Buddha. This isn't because we're Buddhists. We just happen to have a garden Buddha in our borrowed household items. And--it seems fair to offer equal representation for other faiths. We could have just as easily posted a garden gnome outside our door if one had been provided for our use.

## Navigation

My parents ended their lives in a residence community in Duluth, Minnesota. My father experienced difficulties navigating the halls of his residence. There are three possible routes to the dining room, each with additional hallways leading to other wings of the building. There are no street names or hallway signs. Every route is the same color. There are no maps on the walls. He realized one route to the dining room was marked by a large mirror at the far end and thereafter arrived at dinner by walking towards himself. But generally, he was unable to navigate and so stayed in his room.

Streets in older European cities are named, but rarely labeled. If labeled, they have two (or more) names. You *will* be lost on the first trip from hotel to restaurant. Your only hope is to look for landmarks. In Venice, my hotel was a right turn from the street corners marked by a purple umbrella above the panetteria. In Cortona I went to the main plaza, turned right at the church steps and went up the steepest road that did not pass the gelato store. In Japan, I kept the drying persimmons to the right, turned towards the cash machine, then opened the door of my Ryokan--marked with the AC/DC sticker.

Here at my residence, we navigate from cubby to cubby. Leave the dining hall, find the mandala rocks, turn left, look for the blue bird house, then straight on to the buddha.

If I were king of the world, I would hire an iconographer for every residence hall design team. They would comb thrift stores for unusual objects to be posted at every corner in the hall: umbrella, cross, bicycle, snow sled, moose head, sailboat, water ski, flowers, train set, wooden spoons, mixing bowl. Wings of the building wouldn't have numbers or letters (Wing A. Wing B...). They would be destinations: California, New York, Florida, Canada, Germany, Australia. Each wing would reflect that location: palm trees, subways, alligators, snow, lederhosen, kangaroos. No words, just pictures and objects and colors. My father could leave his room, look for the bicycle, turn left at the alligator, go straight until he was in Germany.

In my residence here in Stevens Point, Wisconsin, I walk towards the elevator, turn right, and look for the candy basket.

## The Candy Basket

I live at the far end of the second floor of the independent wing. My mother-in-law lives on the first floor of the assisted wing. Because of this, I regularly travel the length of the building, passing over or through the dining hall, depending on which staircase I choose. If I choose to traverse on the second floor, I pass apartment 237.

I'm not sure who lives in room 237. I may have met them, or possibly not. None of us have our room numbers on a name tag. If it was important to this story, I would find out who this is. but it's not, so I don't.

The resident of 237 hosts a candy basket in their cubby. The basket is white with a woven handle and some pastel accents. A young child could carry it with ease and when I search the internet, I find it listed as a wedding flower girl basket, priced at about ten dollars. At the Goodwill thrift store I've seen entire aisles filled with these baskets, each reasonably priced at two dollars. If you shop Goodwill on half-price days and apply your senior citizen discount, you might obtain one for fifty-cents.

I have never seen the basket of room 237 empty of candy. Before I became involved, the basket exclusively contained small candy bars. The size of the basket restricts the size of the candy. There isn't room for full size chocolate bars. Instead, expect to find bite-sized treats. Think *halloween trick-or-treat.* If you need a serious chocolate fix, Fleet Farm is right across the street. There's a gourmet chocolate shop downtown. Plan ahead.

I wish I had recorded weekly observations on the type and quantity of the contents. It would have made a lovely graph, showing candy consumption over time. Before you fault me for careless data science, consider the optics of digging through the basket once a day and writing notes on a clipboard. In good conscious I would wear rubber gloves, which would be all the more disconcerting to a third-party observer. *"Don't worry," I would say. "I'm not mixing mind-control drugs in with the snickers bars."* I might as well wear a white lab coat and eye protection and sneak around after 6:00 p.m. This would surely alarm my fellow residents and possibly start conspiracy theories.

Instead, I performed a rather unstructured experiment. I purchased peanut butter cups (a personal favorite) and stealthily contributed to the basket. Discovering their absence the next day was every bit as exciting as finding Santa had consumed the cookies and milk my sisters and I had laid out on Christmas eve. Without counting (again--creepy behavior) I observed my contribution was more popular than other brands. Huzzah!

But bags of individually wrapped *fun size* chocolates cost about four dollars and last about two days. This rate of consumption would quickly exceed my research grant, so I looked for alternatives. I found two options: "Dum dums," which are small suckers, cost about half that much. Tootsie Roll Midgees provide an overwhelming piece per dollar value. I purchased a bag of each and seeded the basket.

My experimentation revealed a truth; nobody in my community likes dum dums or tootsie rolls. They are just obstructional flotsam my friends dig through in their search for chocolate. If you have squirrels digging in your garden, you're familiar with the holes and mounds they make. This is the same phenomena I've seen in this candy basket. Holes and mounds. Chocolate bars are picked out; the dum dums and tootsie rolls remain behind.

This may be related to the dental health of my elder friends; tootsie rolls can be problematic with loose fillings or uncertain dental implants. I don't have a workable hypothesis to explain the dearth of dum dum consumption, but it may be related to Kojack's trademark tough-guy sucker-sucking style. If you're going to wander the halls with a sucker sticking out of your mouth, you need to do it with a bit of attitude. Haven't seen it yet, but it wouldn't surprise me.

I have clandestinely observed Lois at the candy basket. She has a walker, so has a convenient place to stash her takings. She's not greedy, but I'm pretty sure she is a regular. Again, I'm not keeping close tabs on this experiment.

I thought of including healthier snacks; bags of nuts, dried fruit, veggie chips. These are on the low end of piece per dollar but I suspect they won't be much more popular than tootsie rolls. And I may be missing the point. The candy basket belongs to the resident of room 207. They aren't running a hotel mini-bar. They are sharing their hope for a brighter world where we offer small gifts to the people around us. Maybe I shouldn't tamper with the universe.

## Hallway Artwork

???EDITS???

Unfortunately, his artwork never made it any further than the museum and his door. Instead of Dave Smith originals, the halls of my residence are decorated with bland hotel art. These prints are designed to be less interesting the longer you look at them. They are chosen so the colors of the art match the paint of the hallway, rather than wall colors which accentuate the art. The corporate Optics and Design department strives for a calming theme that won't disrupt anyone's delicate sensibilities.

This pisses me off. Who the hell made the decision I need to be calmed? Some corporate focus group concluded if residents are presented with visually challenging artwork we will require weeks of therapy. Worse, our children and heirs will initiate lawsuits to collect for mental anguish.

Corporate design teams forget I live with college professors. Poets. Musicians. Librarians. World War II veterans who RAN into combat with a single-shot carbine and a green cotton shirt. I live with men and women who crippled themselves on a potato field but now miss their farm. How dare they present a piece of art intended to calm. me. down. WTF?

I have discovered the current framed art is mounted with adhesive tape - not screws. With one quick yank, I can replace "Pheasant on the Prairie" with "The Persistence of Memory." I can dismount the western landscape and replace it with John Berkey's "Feather Ship." I can banish "Sunset over the desert" and hang "The Sly Shy Spotted Sagacious Snipper Snapper." I can slip down the deserted halls and sow discontent and rebellion.

I think Dave Smith would approve.

## Navigating ???

EDITS???

I would be delighted to test this by inviting the design team over to my residence for lunch. At the door, I would greet them and politely ask them to surrender their eyeglasses and cell phones. Not everyone's eyesight is 20/20 and not everyone is comfortable with GPS. Now we are off to the dining hall. Along the way, I remark on the bicycle, the flowers, and finally the mixing bowl. These are hung on the corners of each hall. After lunch is over (the dining hall is in South America) I thank them for their attendence and tell them they are free to depart. I would abruptly slip away to the security room and observe them re-trace their steps out of the building.

Unknown to my guests, I have enlisted my fellow residents to provide assistance to these tourists. *It's right over there, just past the beach ball. Look for the bicycle.*

I hope they have a chance to appreciate our print of Picasso's "Blue Nude." It's just past the candy dish filled with peanut butter cups.
