---
title: "Dumbo Elephant"
author: "Mark Niemann-Ross"
format: docx
editor: visual
---

It's shortly after ~~lunch~~ dinner and the lobby of the independent wing is quiet. Here at Dimensions Living we keep to a Spanish or Italian schedule: Up early, active until noon, close down between noon and three for siesta, then active until six p.m. Italy and Spain are active much later at night, but lights-out at seven is the modification we have agreed to here in our United States.

The lobby does have its raucous times; Happy hour is here on Fridays at 2:00 p.m. and nickel bingo is Thursday at 6. The weekly activity calendar says there is a town hall meeting here at 2:00 p.m., but right now there are only a few residents. They are checking mail (not email) or reading the newspaper (from a large sheet of paper).

Outside the picture window is an uncommitted Wisconsin thunderstorm, reluctantly displaying sparse cloud lightning, performing distant rumbling, and dropping intermittent rain. Thunderstorms can deliver a more convincing performance, but today we must be experiencing a community-theater level rehearsal. All the parts are correct, but the timing needs work and the percussion section just doesn't have the commitment necessary to really impress the audience. 

I am hanging out in the lobby, and other than being asked to refasten Steve's suspenders, I have no pressing tasks. I'm here to write and watch my senior friends. I could write in my room, but the television wants to display important news and I would be tempted to watch. The independent lobby is more contemplative.

I suppose this place is like a coffee shop, but without the coffee and entrepreneurs. The ventilation system provides white noise and there is just enough muted conversation to keep the silence from becoming noticable.

Dick exits the lobby elevator. Without looking, I know it's him; he carries a personal rock and roll soundtrack supplied by his iPad. It follows him down the hall like an auditory spirit animal, announcing his arrival and departure. When I first began living here, I found this annoying. I was tempted to have a manly chat and point out how this might be overwhelming to other residents. Luckily, I have an aversion to conflict and never brought it up.

I have a big personality. Other adjectives would be "loud," "annoying," or "overwhelming." I *bounce* down stairs. I *announce* when someone comes through the front door. I *shout* at the neighbors. I invite strangers home from the airport (during blizzards) and bring home guinea fowl when my wife is gone for the weekend. I am not a subtle personality.

When I hear Dick's rock-and-roll, I can be sure Dick is still around. When I think about it, my greatest concern isn't the roaming iPad; it's the day when that iPad will no longer roam the halls.

## Dumbo Elephant

Last week, I trotted through this space on my way upstairs. The piano in the lobby was occupied by a large man, possibly thirty-five years old. I didn't get his name so we'll call him Alex. Judith, a resident, sat in a chair next to the piano, listening. Alex is a competent pianist, but I couldn't tell how far his talent stretched as he was only playing simple music. The sort of pieces your first piano teacher would give you to practice left and right hand positions, chord changes, and reading music.

I intruded and asked if they were mother & son.

"Nope," Alex replied. "I'm just up for a while from Midland, Texas. Judith was my piano teacher when I was in third grade."

"He would stay at my place after school," confirmed Judith. "He ran in the front door, threw his coat on the floor, and made a beeline for the piano. I told him he needed to pick up his coat before he could practice."

Alex played some of the songs Judith had taught him. One of them had words; "Dumbo elephant, dumbo elephant, de-dee-de-dee-de-de dahhh." (I wish I did a better job of writing down the lyrics.) He played chords with his left hand, melody with his right. Judith sang along. I was an outsider to their reverie and I excused myself. As I walked away, I heard the piano continue. 

## Visits

I've witnessed a lot of visits from relatives, most of them painful exercises in awkward conversation. Yesterday I was chatting with Anna, who lives just around the corner from the independent wing lobby. She keeps the door to her apartment open and calls out when I walk by. "Whatcha doin?" she asks. "You didn't buy those crap peanuts from Fleet Farm again, did you?"

She's not nosy; just interested. I don't know if she plays sheepshead, but if she asks, don't expect to win.  

Later I see Anna at a table outside with an early-fifty-year old man and a woman who is probably a significant other. A ten-year-old boy is trying to anchor himself to a chair, but ???

"GRANDMA ANNA, IT'S NICE TO SEE YOU!" shouts the man. Anna is not deaf. The woman continues to sit quietly. The boy??? 
