---
---
---

# The Beautiful Math of Random Numbers

## We Think Judy Cheats at Bingo

> *Nickel Bingo Every Thursday Night at 6:00 p.m.*

There are two notable things wrapped up in this sentence. Least of the two, but still significant, is the time: activities here at Dimensions Living occurring past 5:00 are considered late-evening. ~~Dinner~~ Supper is served from 4:30 to 5:30; past that time the halls become the turf of the night owls. Any resident gatherings after six p.m. are surreptitious. Walk unannounced into one of the activity rooms and you may find residents quietly playing Rummikub. But that's just to avert suspicion; when you move out of earshot, they will return to plotting world domination.

Previous to Dimensions Living, these late-night residents would have huddled around the corner table in a seedy bar, speaking in lowered voices and pausing their negotiations when the waitress comes by to refill drinks.

At six o'clock, the sharks circle the waters of Dimensions Living. At six o'clock on Thursday evenings, the sharks forego Rummikub and swim to the Independent Dining Room for *nickel bingo*.

. . .

Nickel Bingo is the second of notable things. There are *other* bingo games during the week, but candy bingo and jewelry bingo are minor-league to nickel bingo. The Dimensions Living bingo sharks occasionally participate, but only to toy with these indifferent residents. If you win at candy or jewelry bingo, you get to choose a piece of candy (or a piece of jewelry). But, *you don't have to put anything in the cup to play*. For these lessor games, you can show up empty-handed and still win. Not so with nickel bingo.

Very few men participate in candy or jewelry bingo. I have asked the activities coordinators if there is ever gun bingo, fishing lure bingo, or whiskey bingo. (answer: *no!*) I'd like to organize an underground bingo association for the men, and the poorly-lit basement parking garage would be ideal for a cigar-smoking, whiskey-drinking, Friday night game. So far, I have abstained from instigating. I don't want to be the cause (or subject) of an *official memo* on appropriate evening activities.

> Official memos come from Jackie, the Facility Director. They are copied on letterhead and appear in your campus mail slot. The instigating resident or precipitating situation is only vaguely insinuated, but the intent is clear: *"Keep it up, buster, and your children will be interviewing other residence halls for your next placement."*

It's essential to understand the basics of the game of bingo if you hope to understand the drama associated with nickel bingo. I'll make this as brief as possible, after which I'll explain why this frequently descends into mayhem.

Simply explained, each player in the room possesses a bingo card displaying a printed matrix of random numbers. The caller sits in front and announces a series random numbers. When a called number matches a number on the player card, the player marks this position. When the marked positions on a bingo card align in a pattern (such as a complete row or column) the player calls out "BINGO." Assuming all the player numbers match caller numbers, the player is a winner. Everyone calls out in amazement and the game is reset.

The random numbers called out are traditionally generated with a bucket of numbered balls, although some impure heathens resort to computer programs. With the bucket-of-balls approach used at Dimensions Living, the caller retrieves a ball, then reads the printed value.

Until recently I did not understand there are different types of bingo. The number of balls used to generate random numbers can vary from thirty to ninety. The rows and columns on the cards, when multiplied, can equal as few as nine positions and as many as twenty-five. Here at Dimensions Living, we play American bingo; seventy-five balls for random number generation and the players use cards with a five-by-five matrix of integers. Each column is topped by the letters of "BINGO." The center square is marked as "FREE."

Your bingo card is randomly selected from a stack. I don't believe you are allowed to bring your own card, although I haven't tried. At the least, it would be a topic of conversation for weeks and might even be the cause of an *official memo*.

Our bingo cards are environmentally-friendly; each number appears in a window with a sliding, transparent-red piece of plastic. When a number is called, you slide the plastic down. When the game is over, you slide the plastic to the top of each window and prepare for the next round.

To play nickel bingo, you'll need a jar of nickels. Quarters, dimes, pennies, and even dollar bills will suffice, but, as you will see, non-nickels cause unnecessary confusion. For God's sake, don't bring foreign currency.

This crowd has unofficially agreed on assigned seating, although there was an *official memo* to the contrary. I advise visitors to sit at a table in the periphery of the room to avoid crashing the normal order; even then, you may find yourself crowding in as the fifth at a table of four. Maybe you should consider just watching, rather than disrupting the clean geometry of two bingo cards per side of the table.

Assuming you've found a table, picture yourself seated at a table with three friends. In front of each of you are two bingo cards. (You could play more, but two seems to be the accepted norm. And I strongly advise you to stick to the accepted norm).

In the middle of the table is a small bowl. It might be empty or it might contain change. If you want to play this round of bingo (and you do, or you wouldn't be sitting at the table) you must contribute one nickel per bingo card. Two bingo cards, two nickels. Four people at the table times two bingo cards will result in eight nickels in the bowl. Which equals forty cents. Instead of two nickels, you are allowed to deposit one dime. If you deposit a quarter, you can remove fifteen cents from the bowl.

Be *inordinately* clear about your action and intention when you make change from the bowl. I believe I've already mentioned mayhem; sudden movement near the group nickel bowl can be misconstrued.

Before each round of bingo can begin, the designated money collector circulates among the tables and gathers the contents of each bowl. It's assumed the money collector confirms each table has contributed the correct amount. This collection is then placed at the head table and the bingo caller can proceed.

*Not so fast...*

You might think this task is inconsequential, but it is not. First, being asked to perform this job is an honor. An informal and self-designated sub-committee of bingo sharks bestows this honor. The qualifications are not available for public review anywhere that I've seen, but I believe the ability to squeeze between the tightly-packed tables is an essential skill. This requires the ability to bend your knees and locomote without the assistance of a walker or wheelchair. I am proud to note I have been asked to perform this task and discharge my duties with the earnestness of first-time student council president.

The task of collecting bingo fees must be done with efficiency; the game is, after all, delayed until this is completed. The sharks are waiting, but not patiently. Pick up the bowl, count the change. That should be simple enough.

*However*. What is the proper response if the change is not correct?

Your first strategy might be to ask if everyone has contributed their two nickels. If you're fortunate, one member of the table will realize it is time to ante-up and contribute their fair share. Unfortunately, this rarely happens.

There are two complexities to consider, possibly more. For example, this table may be assuming that nickels are placed in the cup *after* the money collector has emptied the bowl for the current round. This is an advanced bingo shark technique done in preparation for the next round. Speaking from personal experience, it is easy to become confused about the state of the bowl and you would be mistaken to blame this on any of the seven stages of dementia.

Since you, the collector, are an outsider to the table, you do not have visibility into the intent of the table. You will be unable to audit the flow of cash into the bowl. Your only hope is intervention from one of the table members. Or you can do as I do and just agree everything is accurate, then pour this bowl into the general collection. This isn't an IRS audit, there is no audit trail, the amount you win is secondary to the win itself. Smile and move on.

The other possible event is a change-making anomaly, usually indicated by the presence of a quarter in the bowl and exacerbated by the cumulative arthritis of everyone at the table. Nickels are difficult to pick up when your knuckles are grinding bone-on-bone. To develop empathy, I suggest you insert 60-grit sandpaper between each joint in your fingers so it is excruciating to bend them, then wrap each finger in duct-tape so you are unable to flex. Now pick up three nickels placed in a small bowl to make change for your quarter. As above, I choose to agree everything is accurate and move on to the next table. I'm very popular.

During your training to become certified as a bingo money collector, you'll also learn of the inadvertent bowl collection confusion. Here's a scenario:

1.  Arrive at the table. Develop empathy with the sharks at this table. Assure them they will win during this round.

2.  Someone will need change, most likely for a dollar. Happily count out nickels from the bingo fees you've already collected. Exchange those nickels for the dollar.

3.  Move to collect the bowl from the table. In some cases, someone will object; "You've already collected for this round."

You may think you are *certain* you have not collected. But you are only one vote out of five, the other four being the players seated at the table. They may be assuming the bowl contains money for the next round. The act of making change may have interrupted the normal flow of the interaction between sharks and collectors. Or sadly, there may be some dementia and short-term memory is a bit wobbly.

You might choose to reason through a narrative of the collection. Again, you are one vote out of five. You have no written proof. I believe the correct response is to agree with the majority. After all, it's only forty cents.

At times, someone may be unable to contribute or is somehow flustered with the quick flow of money across the table. I've learned to carry a supplemental pocket of nickels and make a lightning loan where necessary. *"I've got you covered,"* I tell my new friend. Everyone usually forgets about the loan, but the friendship remains.

When the money is collected, the bingo caller can proceed with the announcement of the numbers. Again, let me explain the simple concept, then I'll explain the nuances that lead to shouting.

To call bingo, you have a bucket of numbered balls. In American bingo, you'll have seventy-five balls. Each ball also shows a letter, one of "B", "I", "N", "G", or "O." The letters are non-essential, but assist with the location of the numbers on the bingo card. For example, numbers one through fifteen always appear in the first column, which is labeled "B". Numbers sixteen through thirty always appear in the second column, which is labeled with "I." A typical call would be something to the effect of "G-48." Number forty-eight, if it appears on your bingo card, will always appear in the fourth column, which is labeled with a "G."

If a caller were to announce "N-18" there would be shouting. If you are ever asked to call bingo, don't try this. The sharks understand the numbering system. Do it twice and you will lose your bingo caller certification.

You might think I am kidding about bingo caller certification. I am not. Depending on your place of residence, you may be required to take a class, pass a test, and/or annually renew your license. Search the internet for *bingo certification* for details.

So. The caller will reach into the bucket, withdraw a ball, announce the letter/number combination, then-and this is important-place the ball in the correct place in a master matrix with seventy-five depressions. Each hole is numbered and arranged in five columns of fifteen rows. Each column is labeled with one letter from the word "BINGO." With the ball safely in place, withdraw another ball and repeat the process. The master matrix is an easy way to confirm which numbers have been called. Which is really important when someone calls...

**BINGO!**

. . .

Before we get to the climax of the evening, let's discuss the reality of a live bingo game in the context of a simplified communication model; We'll just consider the sender, noise, and the receiver.

## Sender

Qualities of a good bingo caller - the sender, in this discussion - include enunciation, volume, and pacing - much like an auctioneer, but slower. There is such a thing as lightning bingo-but not at Dimensions Living.

Ideally, the bingo caller will draw a ball from the bucket, then pause to look at the letter/number on the ball, call out the number clearly and carefully, pause, repeat the letter/number, place the ball in the master matrix, pause, shuffle the balls, and finally draw the next ball.

However, some callers have forgotten their training. The worst infraction a caller can make is to be soft of voice or pronunciation. Thirty years of accounting experience might not be the best resume for an aspiring caller. Instead, consider those with experience as pastor, square-dance caller, sports announcer, elementary school teacher, or game-show host.

Pacing is every bit as important as volume and enunciation. If your brain is less than seventy years old, you don't have empathy for the reduction in processing speed of those gathered for Dimensions Living bingo. When I was twenty-years-old, I could do polynomial equations in my head. I could also perform deep-knee bends while lifting seventy-pound weights. Forty years later, math takes longer, just like my knees support less. Pausing between numbers gives everyone a chance to hear the number, parse the number, check both bingo cards, slide the plastic cover on a number, confirm the number with a neighbor, check for a bingo pattern, and re-focus in preparation for the next number.

Imagine if I called out polynomial equations at the pace of one per minute. You might solve the first one. Possibly the second. By the third you would be calling for a pause, and by the fourth you would be irretrievably lost and complaining to your table-mates. Chaos and madness ensue.

## Noise

Communication models include the channel of transmission (paper for writing, copper wires for phone calls, air for sound) and include noise as a complicating factor. Smeared ink for paper, static for phone calls, and rattling bingo balls for bingo callers.

About those damn bingo balls. They are plastic; every time you stir the bucket of balls, you generate a noise akin to a ball-bearing factory. It effectively masks human speech. If you don't pause long enough between calling the number and stirring the balls, you get the following...

"O-63...that's O-(RATTLERATTLERATTLE). The next number is B-3. That's B-(RATTLERATTLERATTLE)."

RATTLERATTLERATTLE results in secondary fallout noise, caused by one or more calls to repeat the last number, followed by 25% of the bingo players repeating the number (out of sync, so the response is also confused) followed by the bingo caller demanding silence, which is followed by another 25% of bingo players again asserting the latest number simultaneous to a different 25% asking if it was a different number, followed by the caller repeating the number, followed by someone asking if that is the last number or the next number. At this time, there is background rumbling about the caller being inaudible or the players needing to pay better attention. I've already mentioned mayhem and chaos.

Also problematic is the arrival of outsiders: relatives, children, nursing staff, janitors. Relatives and children are the worst as they interrupt with no respect for the game in progress. Typically, they appear at the door of the bingo parlor, squeal and call out; "Grandma! We're here!" They invade en-masse, surround their relative and talk loudly about their *car trip* and *how good it is to see them* and *how big the kids have grown* and *we have this pie we baked for you* and *what's going on here* and *Oh, I love bingo* and *we should join in*.

Now, I'm enthusiastic about visitors. They brighten up everyone's day. But *gawdammit*, we're trying to play **bingo** here. ***Nickel Bingo!***

Likewise, the nursing staff are heroes and wrangle medications and blood pressures with grace and care. But the brief interruption in game play means possibly missed numbers, causing one or more calls to repeat the last number, followed by 25% of the bingo players repeating the number ... and so on.

If maintenance is backed up, they may try to vacuum in the next room. The white noise masks the bingo caller's voice, players won't be able to hear, one or more calls to repeat the last number ... and further so on and so forth.

## Receiver

If the caller enunciates, projects, and paces and someone's kids aren't playing with a vacuum cleaner, then everything should go smoothly. However, there is still the matter of the receiver-the bingo player, in this scenario.

By age 80, it's not uncommon to have hearing loss of 50% in the frequency range of the human voice. Roughly one-third of the bingo players have some level of Alzheimers, one of the symptoms being confusion and agitation when dealing with the cacophony of many people talking at once.

------------------------------------------------------------------------

STUFF

(RESIDENT LEAD - These are suggested activities that residents can choose to participate in and are either lead by a resident or done on your own. )

(Why BINGO? Why not FIGHT. TEXAS.)

At times when I am less engaged, my mind wanders through the wonderful math of the game. I teach a statistical programming language called, simply, "R." There are algorithmic rules for the placement of numbers on the board. Each column has a range of discrete integers, each integer can only appear once, the integers must be random in value and occurrence.

I shared this with Janell and she gave me a look I have received only once before. I had excitedly discussed my progress on creating an etch-a-sketch program for the Apple IIe computer, written in assembler. At the time, we were dirt-poor and she failed to see how this could be a career-enhancing pursuit.

As much as I would like to inflict a comprehensive discussion of the programming necessary to generate the bingo matrix, I realize the audience for this sort of thing is limited. Instead, I have added an appendix with code to create a proper bingo card. You're welcome.

## Appendix

Here is R code to build an american bingo card...

```{r}
gimmeFive <- function(range) {
  as.character(sample(x = range, size = 5))
}

BingoMatrix <- matrix(data = c(gimmeFive(1:15),
                               gimmeFive(16:30),
                               gimmeFive(31:45),
                               gimmeFive(46:60),
                               gimmeFive(61:75)),
                      nrow = 5)

colnames(BingoMatrix) <- c("B","I","N","G","O")

BingoMatrix[3,3] <- "Free"

BingoMatrix
```
