---
title: "Red Chair"
author: "Mark Niemann-Ross"
format: docx
editor: visual
---

## Flotsom

Ghosts are portrayed as vengeful, horrifying entities.

Unless they are christian, in which case they are holy.

I think ghosts are one of many echoes of past lives. Some echoes are formal and intentional: tombstones, memorials, buildings, statues. Some are transitory and mysterious: your sense of being watched, strange sounds in the house, objects disappearing and reappearing, dreams of conversations with a deceased. Some are the pressure of things we leave behind: clothing, fishing rods, photos, cremation ashes, toothbrushes, facebook accounts, furniture.

Our apartment at dimensions living includes access to a security cage for large or dirty items. It's located in the basement, next to a large collection of wheelchairs, walkers, assistive toilet devices, and easy lift recliners. I assume these were left behind by former residents. Former, as in *moved on*. I haven't dug for the history, but I suspect these items are no longer useful to the previous owner or their children.

This flotsom rests in an uninteresting pile in a poorly lit and unswept corner of the garage. There's no dramatic lighting, creepy features, or ominous soundtrack to warrant hauntings. Nobody comes down here except to drive their cars.

This is where we met the red chair.

## Theft of the red chair

Amidst the walkers and wheelchairs in the basement is a red, leather, La-Z-Boy recliner. It is in perfect condition, no rips or worn-through patches. The chair has a large wood lever to control the extension of the footrest. Lean back in the chair and it expands to your length. Move to sit upright and it folds out of the way. Its purpose is to make you comfortable; this is why it exists. The chair knows this without the benefit of microprocessor or bluetooth connection.

The only wear-and-tear is a discolored area corresponding to the previous owner's head and faded areas on the arm rests. Echoes of a past life.

It's easy to see how the chair cradled its owner; late night television supplying unwatched light and unheard sound. Both chair and owner rest peacefully until one morning the owner is unable to greet the morning. The apartment is cleaned, nobody wants the chair, and it is hauled to the basement. For the chair, the basement is the opposite of the balloon layer.

::: {.callout-note icon="false"}
## The Balloon Layer

I'm told not everyone knows about the balloon layer. How sad. If you are a parent or grandparent or aunt or uncle, you will need to know this. Give a child a helium balloon. If you don't tie it to their wrist, they will accidentally release it. The expression on a child watching a balloon sail into the distance is photogenic, but distressing. Tears and wailing will ensue.

When this happens, inform the child about the balloon layer. All balloons aspire to join their fellow balloons in this glorious place, but they are held captive in this mortal coil until a child releases them. How grateful the balloon is and how happy this child might be, knowing they have dispensed charity to a simple balloon.

It's a nice story, but if the child is quick, they realize this is an opportunity for a vast magnanimous gesture by purchasing ALL of the balloons and releasing them from their captivity. Or they may race about the playground, freeing balloons from the clutches of less-informed peers.

Back to the red chair.
:::

Janell (my wife) and I stand in the basement and consider the chair. Echoes-the ghost-of the chair's owner whispers a sales pitch. The ghost has an interest in the well being of this favorite chair. *It's mechanically perfect!* whispers the ghost. The chair behaves like any kennel dog being considered for adoption, straightens it's shoulders and looks at us with a hopeful expression. *It's valued at $1,800 dollars retail.* The chair does its best to hide the dust on its arms and seat. *You need such a chair!*

Janell doesn't hesitate. "Get the dolly, we're taking this upstairs."

## Not so fast

Building administration knows about this chair. It has a history and a death sentence. The ghost did not mention the bedbug infestation and appointment with a dumpster.

If I was the ghost, I might be guilty of a similar omission. From staff, we learned this chair was one of a set, its partner had already been disposed. Our ghost had seen the future and-like Marley in *A Christmas Carol*-was doing its best to prevent the repeat of that fate. We unknowingly participated in the clandestine rescue of this chair.

Housekeeping ratted us out. They saw the chair in our apartment and reported its salvation to administration who sent their angels of destruction. Their message was final; We must return the chair to suffer its undeserved fate. The certification of assisted living facilities does not allow bedbugs; this chair was once infested and so must be expunged.

It is unfair to paint administration as the villain in this story. This lone chair threatens the existence of a multi-million dollar assisted living facility, closure of which will result in the unemployment of thirty staff and the expulsion of two hundred residents onto the streets. They are doing their best given the constraints of state licensing guidelines and the boundaries of good common sense. The chair is an innocent victim of government regulation.

Missing from this drama is the actual presence of bedbugs. Like a trip through hell, the chair and the room surrounding it had been heated to 200 degrees. (Bedbugs die at 115 degrees). I am searching for the related greek myth of the story of the hero who has a godly advocate but must pass through the gates of hell before they are redeemed. That's the chair.

We have sat in this chair for five days with no bites. There are no bedbugs. We decide to ignore administration's warning.

It is only a week later when I am stopped in the hall. Our building supervisor informs me if I will load the chair on one of the dollys, he will be glad to remove it. He is polite, but this is clearly not a suggestion. The chair must fulfill its destiny, we may not intervene on its behalf. *Bedbugs. State regulations. Employment. Your mother's best interests...*

I have a photograph of my sleeping mother-in-law in this chair. She is tucked in with a colorful afghan and has an angelic smile. The chair is at peace, it is fulfilling a destiny. In good conscience, I cannot stand by and allow it to be destroyed.

But how?

## Hidden Fugitive

We cannot ignore administration. They have clearly stated their intent and are motivated to make good on their threat. The chair must go.

In the corner of our apartment stands the ghost and the chair, looking at us with hopeful eyes.

What to do? What to do.

Enter Jon, my college roommate. He collects old cars and stray dogs. Actually his wife collects dogs, Jon just collects cars. Dogs and old cars are alike in many ways, except maintenance of the dogs is a fraction of that of the old cars. Jon enters this story with two important assets: he is nearby, and he stores cars in a barn.

A *barn*...

I wrap the chair in plastic and load it into the back of my car, then show up at Jon's with the chair and a six-pack of beer. I leave with neither. I assure him I will return in a month, retrieve the chair and transport it to my home. Jon has experienced many years of my unpredictable antics, but agrees to cooperate. Problem solved!

Our apartment is void of the chair. We invite housekeeping to survey the residence. Everything is as it should be.

Only...there are four depressions in the carpet where the chair briefly resided. An echo.

## An unintended return

Three weeks later we are invited to Jon's home of rambunctious dogs and slumbering cars. Also attending is a frolic of former college roommates. Beer is consumed and old stories are embellished. Sometime between our arrival and the departure of common sense, we decide to move a truck topper from an un-mowed patch to an unkempt room in the barn. This is performed in the same manner as pallbearers carrying a coffin to a grave. It's probable this topper won't move from this resting place for many years--normal for objects in a barn.

Janell doesn't participate in the ceremonial transfer of the topper, but she does observe the final placement of the topper; within eyesight of the chair.

Janell was not in favor of moving the chair to Jon's barn. This was my doing and she unwillingly allowed it to happen. But it is clear she sides with the ghost and the chair, making it three-to-one in favor of the chair residing in front of the television, rather than supplying mice and pigeons a resting and spawning facility.

When I place my corner of the topper in the barn, I turn to observe the ghost and the Janell observing the chair.

"I'm getting the car," they say. Janell is the vocal member of the triad, so she speaks in the singular. "We're loading this up and taking it back." I'm unclear who is the "we" in this sentence, but it will inescapably include me as part of the lift team. I am also included in the unload team, the dolly team, and the elevator team.

The return of this chair means we must banish housekeeping, We need to scrub our own toilet and vacuum our own carpet. It is a small inconvenience considering the comfort of the chair and the pleasure of employing the chair as a platform for evening television.

## New home, same skill

At the end of our stay at Dimensions Living, we transport the chair 1,945 miles to our home in Portland, Oregon. The chair is a good traveler: doesn't require bathroom breaks, doesn't shed or bark, is willing to listen to whatever music or audiobook we choose, and doesn't cost extra when we stay at hotels. Positioned in our living room in Portland, the chair seems to be content. It fulfills its purpose with pleasure, wrapping itself around anyone willing to pause long enough for a pre-bedtime nap.

My younger son, Aaron, came for a visit the other day. He had already heard the rumor of the red chair and was particularly alarmed about the history of bedbugs. He recently experienced his own bedbug episode which resulted in the dumpsterizing of his leather overstuffed lounger. 

He regarded the red chair much the same way you might regard a road-kill deer dragged into the living room.  

"So," he said. He stood somewhat leaned back, away from the chair, hands in pockets. One eyebrow was raised. "This is the chair?"

The chair straightens it's shoulders and looks at Aaron with a hopeful expression.

"It's mechanically perfect!" I say. "It's valued at $1,800 dollars retail. We need such a chair!"

Aaron's posture doesn't change, he isn't convinced. The chair looks from Aaron to me, hoping for reassurance I'll protect it. I pat the back of the chair; no worries, nobody is taking it to the dumpster.

I haven't sensed the ghost since we left Dimensions. I can only suppose the ghost was satisfied with the adoption and went on to wherever it was needed next. But what if it hasn't moved on? Is the distance between Stevens Point, Wisconsin and Portland, Oregon enough to dissuade it from visiting? How do ghosts travel cross-country? Will it come for a social visit? Or will it only appear if we somehow disrespect the chair? 

If I list the chair for sale on Craigslist will a semi-transparent Uber arrive outside our home, discharge its vindictive apparition, then speed away in an attempt to get clear of the mayhem about to be wrought upon those who would abandon the chair? I can only hope for such an advocate when I have bedbugs and become destined for a trip to the dumpster.

Janell and I are considering downsizing to a smaller house. We don't need furniture for two guest rooms, we don't need a table to seat eight, we don't want a lawnmower, and we don't need a couch and four lounge chairs to watch television. But I'm certain we will still need a red chair. Actually, I'm not certain we have a voice in the decision. The chair is with us, until we find it a new home to the ghost's liking. Until then, the chair resides in my living room. 