---
title: Confessions of a Blood Donor
author: Mark Niemann-Ross
format: docx
editor: visual
---

I confess.

I'm a chicken.

Complete with yellow stripes and cold feet.

Not of anything spectacular like falling off of cliffs or being run over by a speeding freight train. Not of Frankenstein or the wolfman or the mummy or of Dracula and all his wives. Not of the IRS or FBI or CIA or even the PTA.

There is only one thing in this teeming world That I am scared of.

Sharp little needles that stick in your arms.

I hammer in nails with asbestos gloves on and I am convinced the sewing machine was Doctor Frankensteins's second creation. But even worse than sweing machines are those nasty people with the evil little sheets asking for blood.

How do you get blood?

With sharp little needles that stick in your arm.

But I was reasonably secure until my 18th birthday. Suddenly, I was legally permitted to give blood and I, be the fool that I am, decided that it was my duty to do this. So I went, yellow stripe and all, to the school gymnasium where the Red Cross had set up a local Blood Palace.

I walked in and sat down next ot one of my buddies. This kid has such active bone marrow that if he doesn't give blood every 60 days, his blood pressure dobules. He has a shunt in his arm so they won't have as much trouble getting to his blood supply. As we moved down the line of chairs toward the blood test, I find that it is getting harder to stand up and easier to sit down. That is, until I find that I am getting dangerously close to the end of the line. Realizing that to grow feathers now means never being able to face the young ladies in the line. I move up to the lady with the poker.

"Is this going to hurt?"

"Hold out your arm."

"Is this going to hurt?"

"(mumble)...AHA...(mumble)"

"Is this going to ... OUCH!"

"You're done."

"That's all?"

"That's all."

And everybody told me this was the hardest part. (Ha...this is gonna be a breeze!)

"Young man, come over here," I walked over to the lady at the desk.

"Have you ever had heart trouble, antibiotics, major surgery, concussion, rubella, blood transfusion, cancer, anemia, leukemia, any sorts of drugs or broken bones?"

"No."

"Take this over there."

And so, following instructions, I walked "over there." I handed in all my cards and paperwork and was given an ominous looking plastic packet. Carrying my packet, courage and heart in my hands, I walked over to one of the green cots.

A smiling face with a red coat motioned for me to lay down. She took my poor, doomed arm and smeared all sorts of something on him. She walked away for a second, came back, put on a tourniquet and gave me a rubber something to bite on.

"No, not ... squeeze that with your hand."

Sheepishly removing the rubber grabby thing from my mouth, I nervously waited for the heart stopping poke in the arm.

A quick stab in the arm and my bag starts to fill up.

From down below a voice filters up. "Sharp pointy thing in your arm...squeeze every 5 seconds...I can feel the needle...very light headed..."

"Breathe into this bag"...halfway done ..."Relax boy, come on, you can do it..."how are you feeling?" "I feel fine, just fine" ...almost done..."Does it stick or sting?"..."Let me fix it for you"..."Breathe in this bag"...arm feeling strange..."Okay"...you're done, I want you to lie there for a minute and breathe in this bag ten times" ... one, two, three, four, five, six, seven, eight, nine, ten ..."Do you feel better now?" ... do I? I think so..."Yes I do" ... "Why don't you go to the snack table and get some cookies and pop"

...cookies? pop? hey, this is what I came for! Show me the way...

I feel myself getting down from the cot and being helped over to the table. Sitting down, the cookies come into focus and my unwounded arm instinctively goes for my just rewards. But then the voice of moderation breaks into my concentration.

"Drink water first. Here's your pin and a booklet you should read. Drink lots of pop, eat lots of cookies and stay here for at least 15 minutes."

"Thanks. Now get out of my way, you're blocking my reach to the cookies."

Everybody sitting at the table is talkative and a little pale. That is, everone except me. I'm happy enough, but;

"Gee Mark. You're just as green as your shirt!"

As a matter of fact, I am feeling a little strange.

"Nurse," I say. "I ..."

Quickly she rushes over and has me lie down on another cot.

"Breathe in this bag ten times."

Not again.

"One two, three, four, five, six, seven, eight, nine, ten."

"Feel better?"

"h...yah."

This, of course, means that it is time to get up and move back to the cook...I mean, recovery table.

Once again, the glass of water appears but after that...

After about 10 minutes of eat, the whole table is ready for another pint but to reveal good health means to be forece on. So sickly, we remain.

"Please, kind nurse, pour me another 7-up, for I seem to be too weak to do it my self...(heh heh)."

But all good things come to an end and the three of us left decided that it was time to move on. And so, making sure that we all had enough cookies to keep us going for the rest of the week, we departed.

Now that I have done this, I look back and realize the experience wasn't as bad as I expected it to be. I'm glad I did it and will do it again. We chickens have to stick together and my advice to you is to lose some of your feathers and give it a try.

What if you were the one who needed it?
