---
title: Mr Graziger
author: Mark Niemann-Ross
format: docx
editor: visual
---

(original probably written \~1976)

"HEYYY Mr. Graziger! Cumere, quick."

Mr Graziger looked up from the pile of graded papers on his desk and wondered what could possibly have gone wrong now. He had spent half an hour helping Karen understand the electronics experiment and then she had spent the last fifteen minutes snickering giggling with Bill, her lab partner. Now he would have to go back and make a few snide comments to her to get her to work again.

he walked back to where they were and when he got there, he paused, shook his head, and wondered how kids ever got through high school. Sitting on the table was a pile of demonstration equipment. Bill and Karen had spent the last fifteen minutes plugging this into that, inserting this thing into that slot, plugging cords in the wall, connecting gas lines to water lines and creating something that Frankenstein would have been proud of. Amidst the jumble he could detect parts of Boyles law, Charles law, Wave Theory, Collision, Electrostatics and in the middle sat a 1000 milliliter beaker wouldn with wire. This beaker had once been unsucessfully used to demonstrate magnetic fields. But now, one wire was connected to a power source and the other end was connected to what looked like an old transistor radio.

Mr. Graziger considered the pile of equipment for a minute, took a deep breath and;

"Tell me Bill, this is very impressive but does it fry hamburgers too?" Karen poked Bill in the ribs with a pencil;

"Funny Mr. Graziger, but if you would like to be awestruck, stand back and watch what Professor William and I summoned you up from the depths for.

Mr. Graziger continued amidst the snickers. "You two should be careful with what you're playing with. Look here, see this?" Mr. Graziger pointed to the metallic ball atop the electrostatic generator; "This thing can make a spark and inch long."

He motioned for the other students to watch. After assuring himself that he was getting some kind of attention, he turned on the generator. Immediately sparks begin to jump between the ball and a ground wire about an inch away. Mr. Graziger had always been intrigued in the generator with it's steady "Pop, pop pop" of discharge and it ws his favorite "toy."

On the side of the desk, a student decided that this was very unintriguing and began to absent-mindedly flip buttons on a small power source.

Mr. Graziger was explaning how many volts was needed to cross a gap one inch long when a roar of escaping air erupted from the pile of apparatus. It was extremely powerful and quick, much like standing in the backwash of a moving train. Just as quickly as the roar came a loud bang sounded and silence followed.

Mr. Graziger straightened his hair, felt for his glasses, realized they had been sucked off by the whirlwind and looked at a disheveled Karen.

"Young lady, what was that?" But all Karen did was sputter and stare.

He surveyed the room again. Several glass jars had been sucked off the shelves, along with his supply of paper towels. No one was seriously hurt that he could see. Then he turned to Karen again.

"Karen, I want to know what you did, what this is, and how I can dismantle your violent brain child."

"After that," he said, holding his head and trying to contain his temper; "you can tell me where I can get my glasses and that flurry of paper towels I saw occupying the air for a brief second."

Her face white, trembling hands covering her quivering mouth; her sputtering changed into a semblence of speech.

"Merrrr GG-Graziger, III-II did-didn't do" was all she culd say. She shifted her gaze away from Mr. Graziger and her wide eyes doubled. She rose a trembling finger and pointed.

There at the end of the line of her finger stood the generator, happily popping away, discharing sparks that directly avoided the inch distant ground and traveled across 5 inches of air to land, glow and join the blue aurora surrounding the glass beaker. The writing glow gave the beaker an appearance of life, as if it would get up from the desk and slither away. Mr. Graziger looked at the object in a state of shock. Feeling the same urge that compelled a caveman to pick up a glowing log and burn his hand, he reachd his finger out to touch the blue glow. As he got closer, he could feel his hair raise. Civilization told him the spark that would arc across would burn the tip of his finger off. But the caveman, ever the master of the unknown, bade him on. He was only two inches away when stray electrons flowing through him begin to gather on his skin, making him a brother to the liter beaker.

Finaly the charge point was reached. He felt his finger grow a mind of its own, he felt his finger prepare to leave him when the accumulated charge very gently picked itself up and, like a wooly cata pillar, delicately transferred itself to the beaker.

No spark, no ear splitting explosion, just a gentle blue arc joining his fingers to the beaker.

He touched it and felt only thebeaker. Round and smooth with the copper wires wouldn around it. Sliding his fingers to the front, he tapped his finger on what seemed to be a hard covering over the opening. It was smooth and felt like pourous bricks. Pressing harder he discoered his finger sunk into the opening. Beneath the blue veil of electrickty he immdiately lost sight of his fingernails.

Reaching his finger further in, it started to become cold. He wriggled his finger, partly to feel things and partly to keep it warm.

Suddenly he withdrew his dripping wet finger with a violence that did Karens shaken nerves little good.

Bill was the first to gather enough wits to demand what had happened.

"It felt like something - like something - *kissed me!*"

Following a straight line that passes through the center axis of the beakker, through an unexplored 4th dimensional tunnel and erupting 20 miles off the northern shore of lake superior and about 10 feet off the bottom of the lake, a 3 foot bottom feeding fish swam placidly away, leaving behind a churning sphere of bubbles rising to the surface, a soggy mass of paper towels on the lake floor, and a pair of glasses with the name "S.P. Graziger" inscribed on the bridge.
