# Greta {.unnumbered}

Greta is my favorite mother-in-law. I've only been married once, and Greta is my *only* mother-in-law, so it's an easy declaration. It amuses me to tell her of this fact. Greta always laughs and give me a hug. She calls me "Marky."

I first met Greta when I was twenty-four years old. Janell, who is now my favorite wife, introduced me to her family. I was way too self-confident to be nervous about how they might feel about me. I had heard stories about her previous boyfriends and I was sure I could easily live up to that standard. As long as I didn't smoke pot in the living room after dinner, I would get high marks. (I could make a funny comment about a "high Mark" - as in a *stoned* Mark - but I'll resist the temptation.)

Greta married Gene after he came home from the Korean war and birthed five children in a small town in Wisconsin. She carried lunch down to his Citgo service station and did the banking for the business. She was steady. Not flashy.

I stand about six-foot, two-inches tall and I'm the tallest of all the Niemann kids. My dad had the nickname of "shorty," which I originally thought was because of his height, but later learned it was due to his haircut. I am genetically like my grandfather, Louie, who stood 6-foot-6 and towered over Ella, his five-foot-and-a-little-bit wife.

Greta is about five-foot-nothing and barely comes up to my shoulder. When I first met Greta, she came out to the front door as I was unfolding myself from the front seat of our Volkswagen Rabbit. She gave me an unflinching hug in spite of the road odor I carried. To return her hug I had to bend over-almost getting down on my knees to equalize our height. She was so damned pleased to meet me. I realized this thing with Janell would probably last.

Janell and I married, had kids, moved from the Midwest to Wyoming, then Colorado, then Portland, Oregon. Janell graduated as a Nurse-Midwife. I pursued software and computers. Gene died when we moved into our Portland home. Greta kept showing up. I told her several times she should just move to Portland. We have a spare bedroom and she loves to clean house. She laughed and turned us down each time.

I'm not sure why I have a close relationship with Greta. We didn't survive a plane crash in the Alps, foraging for food together in the frozen mountains. She didn't donate one of her kidneys to save me from a terminal illness. I've never borrowed money from her. Perhaps once for ice cream. But still, when I see her my heart sings.

I had a tough relationship with my mother, Ellen. I was a moody teenager well into my thirties and only lately have learned how to be less demanding. Communication is difficult for me, I avoid conflict whenever I can. I told a therapist I was avoiding the karmic load of disagreeing with someone. Better to stew in silence than tell someone their actions are unacceptable. Besides, shouldn't I just be more forgiving? Is this really that big of a deal? Much easier to be silently angry.

Ellen's mother came to America from Germany in late 1939 on a vacation. While she was here, World War II broke out. Her mother, my great-grandmother, told her to not come back home. She never saw her parents again. She married a wonderful man, my grandfather, a postman who played trombone. His family assumed she was a German spy, never trusted her, and shunned her. She was understandably depressed and when angry would go silent for weeks at a time.

With a mother that wouldn't speak for weeks, young Ellen must have wondered what she had done. Ellen was desperate for approval and insecure. She thrived on commiseration with friends. And family. When she asked "How are you?" she was not looking for a casual answer. She wanted to know *EVERYTHING*. But not the victories of the day. She wanted the defeats, the sadness, the misery. When I ran in a cross-country race, she wanted to know if I was sad that I came in third place. Was I sad about the math test? Was I sad about my dead pet? Was I sad about what she made for dinner?

Ellen never developed a sense of humor. She scanned every conversation for sadness and defeat. She missed punch lines, absurdities, sarcasm, satire, and puns. After I moved out and gained some distance, I would explain my humor to her. I would tell a joke, then explain the joke. She would think for a minute, realize she was supposed to smile, and smile. Then she would go back to searching for the sadness.

When I moved her out of her house, I came across two teddy-bears with voice boxes. When you squeezed their hand, they would recite an insipid sermon about how it was okay to be sad. It was a creepy reminder of my childhood. I threw them in the garbage.

For a pre-teen/teenager, the constant interrogation was exhausting. I barely knew what these emotions were and was totally unwilling to discuss them for hours. Literally. So I went silent.

My mom, Ellen, learned the craft of silent treatment from her mother and taught it to me. I used it on friends and family until I realized it wasn't a productive means of communicating my displeasure. I still do it. Sorry everyone.

Greta never goes silent. She is vibrant and vocal and I love being around her. But this is a window of opportunity and I know it is closing.
