# Sundowning {.unnumbered}

The first time it happened, we were leaving the wedding of one of Greta's grandsons.

It had been a long and festive event, attended by the entire Ross clan. There are more of them than there are of me. They all know who I am and they take perverse delight in asking trivia questions about their family history. I may be exaggerating, but I am obviously someone who married in. I should have commissioned flash cards and had Janell drill me on names, birthdays, city of residence, five pertinent facts of each uncle and aunt. At the least I should have practiced drawing the Ross family tree on a poster-sized piece of paper.

I have a cousin who excels at this game of *Hūsker Dū?* He will tell you about the party you were at when someone dropped a cake on the picnic table. I will have no recollection of the picnic, nor being at the picnic, nor dropping the cake. At this point, he could tell me any outlandish lie and I would believe it simply because he just seems to know all of this.

This wedding was a massive Ross reunion (as are they all) and I was exhausted. I suspect Janell and Greta were as well. We had rented a hotel room nearby, would get some sleep, and then drive home the following day. Greta was in the back seat, Janell and I in front.

"I cannot believe I have such ungrateful children," Greta suddenly speaks up in the dark. "I am going to give all of my money to charity and you will get none of it."

This was *not* spoken in a teasing voice. Greta was serious and angry. I'd never experienced this side of Greta before. Greta's norm is happy and tolerant, loving and expansive. This was Evil Greta. Who the hell is in the back seat and how am I supposed to react? Remember that I am conflict-avoidant and this was shaping up to be one large conflict. I was happy to be driving.

There *had* been an incident at the wedding. One of Greta's children felt it was appropriate to proselytize to one of the grandchildren and girlfriend. His words were unwelcome and caused tears, leaving the rest of us to mitigate this emotional exchange. Greta may have heard some of the discussion. That's what I assumed this was about. But Greta wouldn't say what was bothering her, only that she was disgusted with us.

Janell and I had no idea where this Greta came from. There were clues, but we didn't know to look for them. At the hotel, she wanted me to get her suitcase out of the car--I had seen her place it in the closet just five minutes before. She asked twice why we were staying in this strange room.

She was angry and sullen until the following morning when we joined some of the grandkids for breakfast. Over waffles, bacon, and coffee she perked up and we were again in good graces. Evil Greta was gone.

In the next months and years, Evil Greta would unexpectedly reappear. We would receive nasty emails and phone calls. The next morning she would be chipper and friendly. She had no recollection of sending us an email about shooting immigrants or the evils of the protestant religion.

In time, we learned this is called *sundowning*. It is an early indicator of dementia, often associated with Alzheimer's disease. Over a short period of time, she became confused with how to operate email and the nastygrams ceased. We didn't realize this was the early days of an inevitable progression.

Greta and her kitchen were legendary. She kept everyone fed and watered from the moment they arrived until departure. Even then, the outbound trip would include a sack lunch. An important part of Greta's persona was her kitchen and mastery of her stove and oven. It was distressing when she lost interest in cooking. It was alarming when she became unable to operate her stove.

"The neighbor's house burned down yesterday," she told Janell over the phone. "It was over on the next block."

"Oh no," Janell said. "What did you do?"

"Oh, nothing," Greta replied. "I could see it burning and I thought *someone should call the fire department*."

"Mom, *You* should have called the fire department!"

"I suppose. How are you doing in nursing school?"

The stove was a start, but this was the incident that convinced the siblings it was time to move Greta out of her home and into senior care. They found a nice apartment in the independent wing of *Dimensions Living* in Stevens Point, Wisconsin. We have a video of Greta sticking out her tongue at us as she unhappily left her home in Neilsville.

Greta didn't thrive at Dimensions Living. She was upset she had to leave her home and live with all these *old* people. Her health declined and she transferred to medical care, then recovered enough to move to rehab. At rehab she declined and entered hospice care. Janell flew out to be with her.

Here's the catch. If you enter hospice, you can't move back to Dimensions Living. They don't have the license or personnel required to provide that level of support. But you can't remain housed at the rehab facility forever, insurance only pays for a limited time. Greta would have to find a new place to live out her days and her options were few.

Here's the loophole. *If the siblings hired 24x7 care for Greta then she could return to Dimensions*. But damn, that's expensive!

There are a few details I haven't mentioned just yet;

Janell retired just a month ago.

Janell has a medical degree.

I have a job which doesn't require I be in any particular place at any time.

What to do.

What to do?
