project:
  type: book

book:
  title: "Life with my friends"
  author: "Mark Niemann-Ross"
  date: "1/22/2023"
  page-navigation: true
  cover-image: cover.png
  chapters:
    - index.qmd
    - redchair.qmd
    - Bingo.qmd
    - candyBasket.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  docx:
    reference-doc: custom-reference.docx

editor: visual

