project:
  type: book

book:
  title: "My Favorite Mother-In-Law"
  author: "Mark Niemann-Ross"
  date: "1/22/2023"
  page-navigation: true
  cover-image: cover.png
  chapters:
    - index.md
    - mnr_aging.md
    - greta.md
    - fires.md
    - sundown.md
    - assistedLife.md
    - siblings.md
    - howIgotHere.md
    - harassingTheNatives.md
    - myMuse.md
    - furnishedApartment.md
    - redchair.md
    - Bingo.md
    - toenails.md
    - hallwayNavigation.md
    - artwork.md
    - ruby.md
    - gretamemorycare.md
    - goodbyeToDimensions.md
    - gretalastchapter.md
    - acknowledgments.md
    - aboutMNR.md

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  docx:
    reference-doc: custom-reference.docx
  epub:
    toc: true
    date: "2023-01-22"
    lang: en-GB

editor: visual

