# The Independent Life {.unnumbered}

Life in the independent wing of Dimensions Living is akin to a college dorm, without the heavy drinking, overactive sexuality, and loud rock music. Maybe it is - I don't have surveillance camera footage to confirm my assumptions. I do know the male/female ratio is in favor of the men; the odds are good, but the goods are odd.

Greta's apartment has a kitchen and her kitchen has the equipment from her previous home. She has the capacity to prepare a meal for thirty relatives, plus sending them home with a bag of sandwiches for the ride home. Seating might be a challenge, she has a total of six chairs.

The unfortunate hair in the lasagna is that Greta has moved in during the Covid pandemic. Dimensions Living is on lock-down. Nobody is allowed to share their viruses and kill their fellow residents. A good call, but a damper on Greta's ability to form friendships with her new community.

But, as Dr. Ian Malcolm dryly observes, "Life finds a way." (Jurassic Park. Look it up.) Dimensions Living simply doesn't have enough staff to police the halls all day and all night.

Bobbi shows up at Greta's door, knocks, and Greta lets her in. Virus be dammed.

"Want to have a beer?" Bobbi asks.

"Are we allowed to drink beer here?" Greta asks.

"I don't know," admits Bobbi. "Let's grab one and sneak into the staircase."

I am not making this up. The Dimensions Living marketing director will attest to the fact of finding Greta and Bobbi in the staircase, drinking a clandestine beer. She asked them why they were sneaking around and got the full story. By the way, independent residents can do anything they damn well please, as long as it doesn't scare the staff. Drinking beer in the staircase, or their room, or the common spaces is allowed. But it's much more fun if it's not.

## Independent. Assisted. Memory.

There is a standard progression of events in a senior living facility. First is independent living; a standard apartment. Independent living comes with housekeeping, maintenance, a meal plan, free bus transportation, and a watchful staff. It's a bit pricey, but only if you don't consider the value of a full support staff.

Next, assisted living looks much the same as independent, but includes enhanced staff involvement. When you don't remember to take your pills or show up for meals, assisted living is there to help. Sitting alone in your room is neither good, nor healthy. Isolation is bad for both body and mind. Assisted living is having the nice lady down the hall checking in on you to make sure you're okay. It just happens the nice lady is part of the staff and has an emergency call button and a nursing degree.

Later we'll talk about the memory care wing. But it's not time for that yet.

## Transition to Assisted Living

The Dimensions Living kitchen staff are efficient and precise. There's a lot of food to prepare and it needs to be served warm - arriving at the table in a narrow window of time. Their budget precludes juggling a fluid schedule of reservations. Show up according to the plan, please, or miss dinner.

Greta wasn't making it to breakfast, lunch, or dinner. Given her history of running *her kitchen* in the way she saw fit, I'm not surprised she pushed back on being told when to show up for meals.

Imagine we are at Greta's house where she raised five children; it is about 3:00 pm.. Greta has already provided breakfast, diaper changing, lunch for Gene, banking for the gas station, vacuumed the living room, possibly re-upholstered the couch. Someone - let's say Janell - finds Greta out in the garden, pulling weeds.

"We need to have dinner ready by 5:30 pm," Janell tells Greta. "And we need to stop serving by 7. Anyone who is late doesn't get to eat."

Greta stands up, tosses the hand full of weeds pulled from the radish bed, and regards Janell. My imagination fails me as to Greta's possible response, but it would be terse. *Nobody* is going to tell Greta when dinner is served. She may be small, but she is mighty, and dinner will be ready when she says it's ready. *Understand?*

So Greta wasn't eating. She didn't venture out of her room. She called her children, telling them she was alone and afraid and hungry. She wanted to return to her home where she knew where the kitchen was and where her friends were and where she could walk to St. Mary's Catholic Church.

She didn't say it directly, but she needed assistance. So her children accommodated her needs. Greta made her first move at Dimensions Living, leaving her apartment in the independent wing for a smaller room in the assisted portion of the building. The staff began looking in to suggest she go for a meal, or mass, or bingo.

She regained weight. She made friends and was invited to sit at table one (an honor). Her world expanded. Assisted living was healthy living.

## The Fall

Greta is nimble. She can stand on one leg to put on her pants. I do yoga so I can emulate her. So far, I'm about fifty-percent crashing into the wall and alarming the household with my feeble attempt at dressing myself. I try not to embarrass myself, but frequently fail.

Greta proceeds through her life with the grace of a ballerina. Maybe I exaggerate; she doesn't have a barre or wall mirror in her apartment. But I dare you to challenge her to a balance contest. She's unnatural that way.

Imagine our surprise when she winds up in the emergency room due to a fall. Nobody knows what happened for sure, but she was probably trying to wash her feet in the sink. One foot to support herself, one foot in the sink. Try it yourself; I'll advise you to put a mattress on the floor to catch you *when* you fall.

Maybe she was performing gymnastic floor exercises. Maybe she was swinging from the light fixtures. Maybe she was working on her *Arabesque* in preparation for the upcoming Dimensions Living talent show.

Nobody knows what happened, but we got a call from the hospital. There were no broken bones, but other things were not good. Her systems were failing. She had infections. She was sundowning - *hard*. She referred to the nurses as *devil's spawn*. She was not a pleasant patient.

Without hesitation, the hospital discharged her to a rehabilitation facility. She was sick enough to qualify for hospice care. Left to herself, Greta was going to die.

The alternative was an all-hands-on-deck twenty-four hours of care, seven days a week. Get her to drink water. Get her up and out of bed. Work on her mobility. Improve her state of mind.

Here's the catch. If you need 24x7 care, you can't move back to Dimensions Living. They don't have the license or personnel required to provide that level of support. But you can't remain housed at the rehab facility forever, insurance only pays for a limited time. Greta would have to find a new place to live out her days and her options were few.

Here's the loophole. *If the siblings hired 24x7 care for Greta then she could return to Dimensions*. But damn, that's expensive!

There are a few details I haven't mentioned just yet;

Janell retired a few months previous.

Janell has a medical degree.

I have a job which doesn't require I be in any particular place at any time.

What to do.

What to do?
