# Hallways {.unnumbered}

There are seven hallways in the residence where I live; three are in the assisted living wing, three are in the independent wing, and one is in the memory wing. Each hallway services six or more rooms. Each room has a door with a small cubby to the side. It's a blank space that invites personal expression by the occupant of the room. Most cubbies have pictures of Jesus or Mary. Many have ceramic dogs or cats (but not both). There are plants and flags and war memorabilia and ceramic figures and wind chimes and drawings by grandchildren.

A few have artwork created by the occupant; our neighbor Jan paints mandala patterns on rocks. Dave Smith, an art professor and member of my community, dabbled in an abstract type of art he described as *Scarabocchio*--Italian for *scribble*. His door was a wild display of politics, opinions, and his multi-colored artwork. His door screamed I AM ECCENTRIC, I AM PROUD OF IT, IT IS WHO I AM. When you are in Stevens Point, Wisconsin, you can visit his museum. I will forever regret not introducing myself to Dave.

I have not seen any lawn flamingos, neon beer signs, dancing hula girls, gum ball machines, coin-operated video games, or historical plaques.

A few cubbies host bird houses. There are no birds flying loose in our building and so the bird houses are empty. But do not underestimate the resourcefulness of my fellow residents. The facility excursion bus makes a weekly trip to a shopping mall. The mall contains a pet store. The pet store contains birds.

For our cubby, I considered an inflatable flappy-arm guy like you see at tire and furniture stores. At 20 feet tall this would crowd against the eight-foot ceiling, plus the one-horsepower fan might generate more noise than my neighbors will tolerate. Instead, I may purchase a target-practice deer with replaceable core from Fleet Farm across the street.

Until I act otherwise, our cubby hosts a Buddha. This isn't because we're Buddhists. We just happen to have a garden Buddha in our borrowed household items. And it seems fair to offer equal representation for other faiths. We would have posted a garden gnome outside our door if one had been provided for our use.

## Navigation

This story is about my time spent in Wisconsin, but in other worlds, my parents finished their lives in a residence community in Duluth, Minnesota. My father experienced difficulties navigating the halls of this place. There were three possible routes to the dining room, each with additional hallways leading to other wings of the building. There were no street names or hallway signs. Every route was the same color. There were no maps on the walls. He was often lost and frustrated and so stayed in his room.

Streets in older European cities are named, but rarely labeled with street signs. If labeled, they have two (or more) names. You *will* be lost on the first trip from hotel to restaurant. Your only hope is to look for landmarks. In Venice, my hotel was a right turn from the street corner marked by a purple umbrella above the panetteria. In Cortona I went to the main plaza, turned right at the church steps and went up the steepest road that did not pass the gelato store. (Note to tourists--there are many steep streets in Cortona.) In Japan, I kept the drying persimmons to the right, turned towards the cash machine, then opened the door of my Ryokan--marked with the AC/DC sticker.

If I were king of the world, I would hire an iconographer for every residence hall design team. They would comb thrift stores for unusual objects and post them at every corner in the hall: umbrella, cross, bicycle, snow sled, moose head, sailboat, water ski, flowers, train set, wooden spoons, mixing bowl. Wings of the building wouldn't have numbers or letters (Wing A. Wing B...). They would be destinations: California, New York, Florida, Canada, Germany, Australia. Each wing would reflect that location: palm trees, subways, alligators, snow, lederhosen, kangaroos. No words, just pictures and objects and colors.

My father could have stepped out of his room, looked for the bicycle, turned left at the alligator, gone straight until he was in Germany. He eventually realized one route to his dining room was marked by a large mirror at the far end of the hall. Thereafter he arrived at dinner by walking towards himself.

Here at my Wisconsin residence we navigate from cubby to cubby. Leave the dining hall, find the mandala rocks, turn left, look for the blue bird house, then straight on to the buddha. To get to the dining hall at my residence here in Stevens Point, Wisconsin, I walk towards the elevator, turn right, and look for the candy basket.

## The Candy Basket

I live at the far end of the second floor of the independent wing. My mother-in-law lives on the first floor of the assisted wing. Because of this, I regularly travel the length of the building, passing over or through the dining hall, depending on which staircase I choose. If I choose to traverse on the second floor, I pass apartment 237.

The resident of 237 hosts a candy basket in their cubby. The basket is white with a woven handle and some pastel accents. A young child could carry it with ease and when I search the internet, I find it listed as a wedding flower-girl basket, priced at about ten dollars. At the Goodwill thrift store I've seen entire aisles filled with these baskets, each reasonably priced at two dollars. If you shop Goodwill on half-price days and apply your senior citizen discount, you might obtain one for fifty cents.

I have never seen the basket of room 237 empty of candy. Before I became involved, the basket exclusively contained small candy bars. The size of the basket restricts the size of the candy. There isn't room for full size chocolate bars. Instead, expect to find bite-sized treats. Think *Halloween trick-or-treat.* If you need a serious chocolate fix, Fleet Farm is right across the street. There's a gourmet chocolate shop downtown. Plan ahead.

I wish I had recorded weekly observations on the type and quantity of its contents. It would have made a lovely graph, showing candy consumption over time. Before you fault me for careless data science, consider the optics of digging through the basket once a day and writing notes on a clipboard. In good conscience I would wear disposable gloves, which would be all the more disconcerting to a third-party observer.

"Don't worry," I would say. "I'm not mixing mind-control drugs in with the Snickers bars."

I might as well wear a white lab coat and eye protection and sneak around after 6:00 p.m. This would surely alarm my fellow residents and possibly start conspiracy theories.

Instead, I performed a rather unstructured experiment. I purchased peanut butter cups (a personal favorite) and stealthily contributed to the basket. Discovering their absence the next day was every bit as exciting as finding Santa had consumed the cookies and milk my sisters and I had laid out on Christmas Eve. Without counting (again, creepy behavior) I observed my contribution was more popular than other brands. Huzzah!

But bags of individually wrapped fun-size chocolates cost about four dollars and last about two days. This rate of consumption would quickly exceed the value of my research grant, so I looked for alternatives. I found two options: Dum Dums, which are small suckers and cost about half the price of small chocolate bars. Tootsie Roll Midgees provide an overwhelming piece per dollar value. I purchased a bag of each and seeded the basket.

My experimentation immediately encountered a problem; nobody in my community likes Dum Dums or Tootsie Rolls. They are just obstructional flotsam my friends dig through in their search for chocolate. If you have squirrels digging in your garden, you're familiar with the holes and mounds they make. This is the same phenomenon I've seen in this candy basket. Holes and mounds. Chocolate bars are picked out; the Dum Dums and Tootsie Rolls remain behind.

This may be related to the dental health of my elder friends; Tootsie Rolls can be problematic for loose fillings or uncertain dental implants. I don't have a workable hypothesis to explain the dearth of Dum Dum consumption, but it may be related to Kojack's trademark tough-guy sucker-sucking style. If you're going to wander the halls with a sucker sticking out of your mouth, you need to do it with a bit of attitude.

I thought of including healthier snacks; bags of nuts, dried fruit, veggie chips. These are on the low end of piece per dollar but I suspect they won't be much more popular than Tootsie Rolls. But I may be missing the point. The candy basket belongs to the resident of room 237. They aren't running a hotel mini-bar. They are sharing their hope for a brighter world where we offer small gifts to the people around us. Maybe I shouldn't tamper with the universe.

## Hallway Artwork

In one of many trips between my apartment and my mother-in-law's apartment, I noticed the artwork hanging on the walls.

The halls of my residence are decorated with bland hotel art. A classic example is "Hunting Grouse." It's a wash of fall colors, mostly orange fading to brown. There is, predictably, a grouse in flight and a hunter in the distant background. The bird is flying to the left, the hunter is walking to the right. The subjects of the painting are trying their hardest to get out of this mundane print. I take their suggestion to heart and keep moving.

These prints are designed to be less interesting the longer you look at them. They are chosen so the colors of the art match the paint of the hallway, rather than choosing wall colors to accentuate the art. The corporate Optics and Design department strives for a calming theme that won't disrupt anyone's delicate sensibilities.

This pisses me off. Who the hell made the decision I need to be calmed? Some corporate focus group concluded if residents are presented with visually challenging artwork we will require weeks of therapy. Worse, our children and heirs will initiate lawsuits to collect for mental anguish.

Corporate design teams forget I live with college professors. Poets. Musicians. Librarians. World War II veterans who RAN into combat with a single-shot carbine and a green cotton shirt. I live with men and women who crippled themselves on a potato field but now miss their farm. How dare they present a piece of art intended to calm. me. down. WTF?

I have discovered the current framed art is mounted with adhesive tape - not screws. With one quick yank, I could replace "Pheasant on the Prairie" with Dali's "The Persistence of Memory." I could dismount the western landscape and replace it with John Berkey's "Feather Ship."

Remember Dave Smith? He was the Scarabocchio guy and a former resident of Dimensions. Were he still alive, I would sneak to his door late at night (after 6:00 pm) and invite him to help me replace bad with good.

This artwork rebellion would require help. A resident at the far end of the building could push their pendant, summoning the late-night staff. It takes about ten minutes to walk from the staff room to the far apartment, reset the pendant, then return. Dave and I would have about five minutes to remove "Sunset Over The Desert" and hang "The Sly Shy Spotted Sagacious Snipper Snapper."

I estimate there are ten prints per hall. The memory wing doesn't have wall art, and the independent wing doesn't have staff (we assume we can do what we want with artwork in the independent wing, although that may not be true). That leaves three wings with about thirty prints Dave and I would have to clandestinely replace. This presents three problems: our artwork supply, willing accomplices, and movement of the artwork.

Thirty prints is a lot of artwork. This isn't stuff you find at Fleet Farm; you have to procure it. I'm guessing residents have favorite artwork stored with children and would now like it placed in our hallways. Janell and I have been entrusted with one such piece. I'm sure Alberta, the former owner, would take delight in the wickedness of the entire project and approve the donation.

I'm certain we can enlist residents to distract the staff. The pendants are known to randomly trigger so the consequences of a button push are minimal. If we have a cadre of five button-pushers, we should be good to go.

Imagine our logistics-director-in-charge-of-art-replacement standing in front of the white board in the activity room. A floor plan of Dimensions living is sketched out in red dry-erase marker.

"Our target is *Western Sunset with Cowboy* hanging outside of the director's office," says our logistics director. She draws a green circle on the floor plan. "Bob, you'll move to the end of the independent wing, second floor, right near the elevator." A black circle indicates Bob's position.

"Gladice, you'll position your strike team, identified as *alpha team*, in the first floor unisex bathroom. You will have the substitute Picasso *The Three Musicians*."

"I don't like the unisex bathroom," says Gladice. "It doesn't get cleaned often enough. Can we use the women's bathroom instead?"

"The women's bathroom is thirty feet away from the target," says our logistics director. "The unisex bathroom is right across the hall. Given that everyone in the strike team is using walkers, the distance is critical. Use the unisex bathroom, you'll need the extra time."

"Zeta Team," she continues. "You will be in the auditorium for the late-night movie. At precisely 8:00 p.m., Bob will trigger his pendant and you discretely leave the movie and move towards Alpha team." The Logistics director draws a black box with arrows pointing in the direction of movement. "Don't mess this up again. The movie is supposed to be *Titanic*. If you don't want to miss the conclusion, watch it beforehand."

"Zeta team will pass the staff heading towards Bob. When Zeta team reaches the target, they will remove *Western Sunset with Cowboy* and proceed to room 423 - which is the designated drop zone. Leave the print under the bed. Return to your rooms via different routes."

"When you pass the unisex bathroom, knock three times," Logistics demonstrates this knock on the table top. "Alpha team, that is your signal to hang your substitute."

"Remember, you can't be quick, so be efficient," she caps her dry-erase marker. "Any questions?"

There is the issue of moving thirty new prints into the building and moving the replaced artwork out. Administration or staff are going to take note of the arrivals, even if spaced out over time. Taking the old prints to the dumpster is sure to be noticed, especially since transporting a large print on a walker would be a dead giveaway of the nefarious plot.

I won't disclose how this would be accomplished. But if I were trying to curtail this project, I would be suspicious of sons or daughters with a pick-up truck and a tarp. Maybe that Sunday afternoon visit isn't *just* taking grandpa out for lunch...

## The Beauty We Miss

For art to be appreciated, you must spend time with it. Flipping through a coffee-table book about the Louvre will not reveal the wonder of the Mona Lisa. You must spend time looking at her eyes. You must see the delicate veil over her hair. Who else was in the studio? Why is she smiling?

To appreciate the community I live with takes time. You can't wander through on a Sunday afternoon and hope to notice subtle details. You will walk by the artwork of the grouse and hunter but never see it. You might take a piece of candy, but which piece? And why? You'll never look up and notice the umbrella at the corner of California and Florida. If your aging parent bothers to explain this umbrella, you might dismiss the whole story as another symptom of an aging mind.

You can't just march in and expect the world to reveal itself at your demand. Instead, you must be patient and allow the hallway to unfold as it is ready. There are comfortable chairs--you should try one for a bit of time.

Later, when you depart, would you do me a favor? If you see any artwork around the rear of the building, please discretely place it in the back of your pickup. You may keep it or dispose of it as you see fit. Strike Team Zeta appreciates your assistance.
