# Kitchen {.unnumbered}

Greta and her kitchen were legendary. She kept everyone fed and watered from the moment they arrived until they left. Even then, she would pack a sandwich for the trip. Gene would meet us down at his gas station and fill our tank. I swear that Korean Veteran had a tear in his eye as we drove away from his gas pumps.

An important part of Greta's persona was her kitchen and mastery of her stove and oven. For thirty years, she cooked three meals a day without fail and without complaint. I wasn't there to observe the early days, but I can only imagine the uproar of forcing breakfast down the throats of five pissy children late for school (plus changing diapers on at least one, sometimes three of the offspring). Gene did what he could, but sometimes it's best to stay out of the way of the choreography happening in the kitchen. Gene was a wise man, ate the breakfast he could get, and went to his gas station.

Breakfast wasn't the end of it. Greta walked a packaged lunch to Gene every day, ran a few errands for him, did the banking, then turned back home to prepare dinner.

I have first-hand experience on what Greta considered an acceptable dinner. It wasn't fancy, but it was plentiful and satisfying. It was delivered to the table with the timing of a professional chef. It was warm. Gene said grace, and Greta always added how she was lucky to have such a good provider in Gene. I remember thinking that if I was to continue this relationship with Janell, there were pretty clear expectations of my role in any resulting marriage.

I don't recall any of the siblings pushing back on dinner. We ate what was placed in front of us, and there was usually a bit left over.

"Eat it, then it will be gone," Greta would say, passing the entree and salad around the table a third time. The refrigerator was full of leftovers from yesterday - until she brought out plates for snacking on during the evening family game.

For many years, I participated in software tradeshows. These were enormously over-blown events, monuments to the egos of the company presidents, pundits, and companies pushing the latest and greatest. A trade show was a nightmare of logistics and last-minute stress-inducing capriciousness. One company president decided the color of the booth was all wrong and forced his employees to repaint the evening before the show. This is just about the equivalent of deciding to remodel the kitchen the evening before a Thanksgiving dinner. Complete madness. It brought young people to tears. I'm not kidding.

Greta would have handled it. The booth would have been painted. And pinstriped. And she would have fixed lunch for the out-of-his-mind CEO who suggested a repaint in the first place. Then she would have headed back home to prepare dinner for her family.

That's Greta.

## Fire

Greta lived alone after Gene died. She moved to a new house a few blocks away. We would visit and noticed she was willing to let us cook. Over time, she *expected* we would cook meals. Slowly, we picked up clues her interest in the kitchen was waning. For anyone else, this might be just a symptom of living alone. But this was unsettling for those of us who knew Greta.

"The neighbor's house burned down yesterday," she told Janell over the phone. "It was over on the next block."

"Oh no," Janell said. "What did you do?"

"Oh, nothing," Greta replied. "I could see it burning and I thought someone should call the fire department."

"Mom, *You* should have called the fire department!"

"I suppose. How are you doing in school?"

This was the incident that convinced the siblings it was time to move Greta out of her home and into senior care. They found a nice apartment in the independent wing of Dimensions Living in Stevens Point, Wisconsin. We have a video of Greta sticking out her tongue at us as she unhappily left her home in Neilsville.
