# Only Two Months {.unnumbered}

Janell and I have an open-ended lease of this apartment and could stay here as long as we wish. It's expensive, but comfortable and convenient. We make an enormous difference in Greta's quality of life. It's a tempting place to spend a year.

But we have a life in Portland. We have friends, an ocean, a house, a neighborhood. Our neighbor dog sticks his head through a hole in the fence and whines for biscuits. Our chickens lay eggs when they feel inspired. We belong to clubs and a church. All of that is on hold until we return. We can't do it online.

I'm watching Zero chase the squirrel for the last time this summer, possibly this year, possibly forever, depending on Tom and Pauline. Everything we bought from Goodwill has been returned and I vacuumed the carpet for the last time.

Saying goodbye to our friends takes too long and should go on forever. This is well documented in paintings, music, and poetry, so I'm not taken by surprise \[WHAT? EXPAND\]. But oh, that final walk through the dining hall is hard.

I exchange last jokes and stories. I look into Gladice's eyes. But the best moment is when Ray walks by.

Ray watches too much opinion television and likes to discuss the latest conspiracies. He wears a baseball cap. We explore stories with our two different viewpoints. We always part with a laugh and agree it's up to us. Ray is a hard-won, and most valued friend.

Ray uses a walker, and deviations from a direct path are an extra effort for him. He gets up from his table in the corner and begins the walk back to his room. This time he drifts to the right, away from the exit, towards where I'm sitting with Gladice.

"I hear you're leaving," Ray says.

"Yep," I agree. "Leaving in about an hour."

"Well... I'm going to miss you." That's it. He heads back to the exit. But what more does he need to say? It's a sonnet in six words.

This is the last time I will see some of these friends, but I don't know whom \[WHICH ONES?\]. \["TRINKETS" NEEDS A BETTER SETUP\] I have a box full of special trinkets; marbles, figurines, medallions, agates, cheap jewelry. Every day, one of those trinkets might disappear. Someone might come by and take one. Or not. I never know and I never get the choice. If I neglect to look at a trinket one day, I may not see it ever again.

When they were still alive, I was sitting in my parent's living room, talking to them about the task I dreaded when it would come time to move them to assisted living. My parents had amassed an extensive collection of art, furniture, books, and souvenirs. I was encouraging them to give it all away to charities or goodwill.

"You should take the things you want," said my mother. I lived in the other corner of the country, three thousand miles away. Hauling keepsakes across that distance was impractical. Besides, I had a house full of my own possessions.

"Thanks, but that's just not possible," I said.

"Don't worry," my dad responded to my mom. "When you die, I'll just back up a dumpster and throw everything away. You don't have to worry about the burden on your children."

I don't know why he didn't reach over and slap her as well. I mean, I never saw him hit my mother, but this was just as painful.

The dumpster fodder my father was tossing out was more than art and furniture. My mother had carefully bestowed meaning onto each item. Like an urn filled with the cremated ashes of a beloved relative, each dish and each chair contained the echo of a precious person, place, or thing. We could point to any item and she would relate the story of a picnic with a special friend, or the time she went to visit her favorite aunt's house and had a special cookie with tea.

Throwing out the broken rocking chair was ending the physical existence of Grandma Gaebbert. \[GREG MOORE SAYS NEED MORE\]

\[NEEDS TRANSITION\] Leaving Dimensions Living might end the last existence of one of my friends.

I don't know if Ray's baseball cap will go missing from my box of treasures. I don't know if he will be here when I get back. It makes leaving here all the more difficult.

\[NEEDS TO BE A BOOKEND\]
