# Greta {.unnumbered}

I've only been married once, so Greta is my *only* mother-in-law. It amuses me to tell her of this fact. Greta always laughs and give me a hug. She calls me "Marky."

Greta was born in 1934 and born in Marshfield, Wisconsin. She grew up on a farm (as did everyone in Wisconsin in 1930). Her father maintained a small dairy herd and opened a roadside tavern where she helped served roasted chicken and beer. Her dad served minors, although he was quick to tell these kids "you've had enough." He was also protective of Greta, reminding everyone to watch their language because there were women present. She loved her Dad; he would take her to town when he went there for business and buy her a treat. Her sister was jealous, and Greta told her Dad would take her as well - she just needed to ask. Apparently she never did.

Greta was one year old when the Social Security Act was passed. When she was sixteen a vaccine for polio was invented and tested. She went to college to become a teacher.

Greta has told us (several times) about her experience in teacher's college. She was in charge of at least one of the annual trips and we have seen the pictures, diary entries, and budget. Greta was quite the sparkplug, singing and dancing until early in the morning, then getting her fellow students up and in the busses for another day driving through the mountains.

Eugene Ross returned from being stationed in the Chorwan Valley during the Korean War. He had a piece of shrapnel in his arm, but never talke about his experiences.

Greta married Gene after he came home from the Korean war and birthed five children in a small town in Wisconsin. She carried lunch down to his Citgo service station and did the banking for the business. She made dinner and thanked the Lord for such a good provider as Eugene Ross.

Her children, like all children, tested her limits. Her middle son memorized joke books and would repeat them, rapid-fire, at the dinner table. When the kids were laughing, choking, and spitting up milk from their noses, Gene sent them to the basement. I like to think Gene and Greta would sit at the quiet table, trying to keep an air of somber wisdom, but eventually smirking and then breaking out in snorts. Parental decorum *must* be maintained.

One daughter was famous for climbing down from her second-floor bedroom via the antenna mast next to the house. She was sneaking out for parties. She had to avoid the nearby kitchen window, especially if anyone was doing late night dishes. Once, upon her return, she was halfway up the mast when a passing car caught her in its headlights.

One son collected beer cans. A *lot* of beer cans; empty ones. *Who emptied all those beer cans?*

## Greta has no trust issues

Greta and I conversed over the phone a year before I met her in person. I had returned from a trip and wanted to follow up on a potential romance with Janell Ross, but didn't have her phone number. This was before the internet, so I went to a phone booth and called directory assistance - 411 for those who don't remember the number.

"Directory assistance," said the operator. This was a real person - not a recording, not an AI. "What city are you calling?"

"Um, Neilsville, Wisconsin?" I had a letter with a return address of Neilsville, so I assumed I could reach her there. "I'm looking for Janell Ross."

"I don't have a Janell Ross. I do have a Eugene Ross. I can connect you with that number."

"That works." The phone clicked and rang. A voice answered.

"This is Greta," says the voice on the phone.

"Hi Greta," I say. "I don't think you know me, but I'm trying to call Janell. Can I get her phone number?"

Greta doesn't ask me if I'm a stalker, or suggest I could give her *my* phone number and she would pass it to Janell, or anything related to protecting her daughter from miscreants. She doesn't pause before giving me Janell's phone number in Green Bay, Wisconsin. It didn't occur to me she should be a bit less trusting than she was.

That's Greta.

## Meeting Greta

I first met Greta when I was twenty-four years old. Janell, who is now my favorite wife, introduced me to her family. I was too self-confident to be nervous about how they might feel about me. As long as I didn't smoke pot in the living room after dinner, I would get high marks. (I could make a funny comment about a "high Mark" - as in a *stoned* Mark - but I'll resist the temptation.)

I stand about six-foot, two-inches tall; the tallest of all the Niemann kids. My dad had the nickname of "shorty," which I originally thought was because of his height, but later learned it was due to his haircut. I am genetically like my grandfather, Louie, who stood 6-foot-6 and towered over Ella, his five-foot-and-a-little-bit-short wife.

Greta is about five-foot-nothing and barely comes up to my shoulder. When I first met Greta, she came out to the front door as I was unfolding myself from the front seat of my surplus postal jeep. She gave me an unflinching hug in spite of the road odor I carried. To return her hug I had to bend over-almost getting down on my knees to equalize our height. She was so damned pleased to meet me.

Janell and I married, had kids, moved from the Midwest to Wyoming, then Colorado, then Portland, Oregon. Gene died shortly after we moved into our Portland home. Greta kept showing up. We have a spare bedroom and she loves to clean house. I told her several times she should move to Portland. She laughed and turned us down each time. I wasn't kidding.

Greta and I had one particular conversation I remember. We were walking on the Oregon coast, just the two of us. We got to talking about abortion and her Catholic faith. I'm Presbyterian, but she never held that against me. I was explaining my stance on abortion, expressing my belief abortion was a medical issue and was a decision between a woman and her doctor. The church she belongs to was unwavering in the belief that abortion was wrong. But we had an open and respectful discussion about the issue, she gracefully accepted my thoughts, which gave me encouragement to accept hers.

## Religion

Janell grew up Catholic. I grew up Presbyterian (a liberal flavor of Protestant). When we married, we decided to do it in my childhood church, North Como Presbyterian Church in Roseville, Minnesota. We enlisted a Presbyterian minister and a Catholic Deacon to officiate.

In response to the wedding announcement, we received a letter from Janell's aunt, who shared her disappointment that Janell was marrying outside the Catholic religion. I suppose she expected I would convert to Catholicism. The Catholic church, for their part, refused to allow me to participate in Catholic sacraments since I was a protestant outcast. My emotions have mellowed over the years, but I still clench my teeth when I recall the conversation with the Catholic Father who informed me I was *persona-non-grata* and would have to remain seated in the back row of the sanctuary. The internet provides pages of rationalization about why this is, but none of it dampens the sting of being told I'm less than perfect in God's eye. Fuck you, Catholic church.

But then, there's Greta. She never brought this up. Never. Not once. She loved me for who I was. She overlooked my faith, my bad hygiene, my goofy dress code; so many things I regret as I age. She only saw the man her daughter loved and the potential I had as a son-in-law.

I'm not sure why I have a close relationship with Greta. We didn't survive a plane crash in the Alps, foraging for food together in the frozen mountains. She didn't donate one of her kidneys to save me from a terminal illness. I've never borrowed money from her. Perhaps once for ice cream. But still, when I see her, my heart sings.

I'm sad our time together is drawing to a close.
