# Angels Among Us {.unnumbered}

As part of our rehabilitation efforts, Janell and I have been taking Greta on walks. She slouches over her walker.

"Walk like a super model," Janell tells her. "Tits Up!"

Greta and Janell laugh; I try to maintain a sense of proper son-in-law decorum. Greta straightens her back, and we resume our walk.

## Eloping

Greta improved from struggling out of bed to walking around the parking lot. Buoyed by success, I have decided to enlarge our territory. Greta and I walk to the end of the sidewalk and instead of turning left to circumscribe the parking lot, we turn right towards the garden center on the next block. It's an ambitious goal, but I'm confident she will make it. If not, she can sit on her walker and I could push her home.

She struggles with the distance, but makes it. We are rewarded with a stroll through the nursery and she mentions some of the vegetables she'd like to plant this next year.

This all seems like a great achievement until I am called into the ~~principal's~~ administration office the next day.

"Mark," the administrator of Dimensions Living says. "We saw you walking Greta around the block yesterday."

"I know," I say, filled with pride. "By next week we can be walking to the shopping mall!"

"There is a problem," she says. "You are helping Greta become used to travelling off the property. She may wander off and forget how to get home. If she returns to Dimensions in the back seat of a police car, we have to either place her in memory care or she has to find a new place to live. And right now, we don't have any room in memory care."

Again, I am being told to *straighten up, buster*. Nicely, but the message is clear.

When residents wander off-property, this is called "eloping." It is different from the high-school ill-advised marriage activity. Like marriage eloping, participants sometimes get lost and sometimes get in trouble. Families become upset and take legal action. That's bad. I shouldn't be teaching Greta to do this.

## Late Nights

Greta has been wandering the halls of Dimensions Living. Normally not a problem -- I wander the halls as well. The difference between Greta and me is that Greta shouts "HELP. WHERE IS EVERYBODY?" The staff helps her get back to her room and safely back in bed.

Yesterday, the staff saw her heading out of the parking lot. They sent a staffer (named Joan) to chase her down.

"Greta," says Joan. "Where are you going?"

"I'm heading to the cafeteria," she responds without stopping. "I'm late for lunch."

It's actually dinner time, and she is heading for the highway. Neither are good indicators. Actually, both are clear indicators; it's time for Greta to move to the memory care unit.

This is uncomfortable. Greta is chatty and social. Most of the folks in memory care are neither. Worse, Greta knows what memory care is all about. She's been back here to visit some friends and was able to carry on one-way conversations. She was relieved to make it back out of the locked doors keeping these residents from wandering into the street.

Her children concoct an elaborate plot to move her into her new apartment. Some of us take her out for the weekend. Others take advantage of her absence to carry things to the new place and store things she won't need or that won't fit. On Sunday evening, we return with Greta.

Instead of turning right, we go straight into the memory care wing.

"Where are we going?" Greta says. She points to the right. "My apartment is that way."

"Mom," Janell says, and heads towards the locked door. "Let's go look at your new apartment."

This new apartment is like my college dorm room. It has a shared bathroom and opens into a central space. There is a large television and sitting area. There are always people to talk to. There is a well-tended garden and patio for sunny afternoons.

Unlike my college dorm, there is a 24 hour kitchen and staff to make anything the residents request.

And the door to the outside world is locked.

Greta is in transition. She isn't able to manage on her own and the staff in this wing provide the things she needs. But she is conversational. Much more so than her peers. She simultaneously doesn't know enough and also knows too much.

I join Greta at mealtimes and chat while she eats. At one of her first days, we had a discussion about "this place."

"Why am I here?" she asks me. "What test do I have to take to get out and back to my old apartment?"

"It's not a test," I tell her. "It's because part of your brain doesn't work. This place is like your walker. You use it since your legs don't work like they used to. This place, and the staff here, help you with the things you aren't able to do on your own. There are things your brain doesn't remember anymore."

"I don't need this," She says.

"Where are you living right now?" I ask her.

"I don't know," she admits.

"You are in Stevens Point," I tell her. "How is your lunch?"

"It's not good. The beans are dry," She pokes at the beans. If there were a dog nearby, she would clandestinely hand the beans to the dog. But she never allowed dogs in her house, so perhaps she never learned that trick. Or the kids never had a dog precisely because she knew that trick.

"How about the meat loaf?" I ask. She has eaten most of it already.

"It's not as good as mine," she laughs.

"Where are you living right now?" I ask her.

"I don't know," she admits. She doesn't remember I just told her the answer.

I'm trying to make a case for why she needs memory care; ironically, because she needs memory care, she can't fathom my logic. I change the topic.

In a few months, Greta will slip below the cognitive threshold where the lack of conversation with her peers bothers her. She engages with more activities than when she was in assisted living. She gets more personal attention from the staff. When she gets up at night, there is always someone to reassure her that she isn't alone. They ask her if she would like a snack and a glass of juice. They listen to audio books with her.

Greta is surrounded by caring people. They don't just know *about* Greta. They like her and care for her with enthusiasm and sincerity. She calls me her favorite son-in-law, but I know she has many "favorite" people in her life.

My mother called them "angels among us." I am honored to be one of them.
