# How I Got Here {.unnumbered}

I'm a resident of Dimensions Assisted Living Facility. I've been told I'm an interloper; an outsider to this community with no hope of integrating for another twenty years. I've had it pointed out to me that my knees still work, that I do yoga balance poses without sitting down, and that I (occasionally) win at pickle ball. I'm *only* sixty-five years old, I can eat and drink pretty much what I like, and I stay up past 9:00 p.m.

But still, I'm a resident of Dimensions Assisted Living Facility. For two months, I have been the youngest resident of the senior community where my mother-in-law lives. How did this happen?

## **Fungi**

My mother-in-law Greta is an absolute hoot. Mostly, she laughs at my jokes and I can kid around with her. When Janell (my wife and Greta's daughter) visits, Greta looks around behind her to see if I'm also visiting. If I am, Janell is dismissed and I get the first hug. I've told Greta she is my favorite mother-in-law (she is my *only* mother-in-law) and she agrees that I am her favorite son-in-law. (My apologies to the other son-in-law).

Greta is losing her mind. It's more accurate to say she is losing her linear sense of time. As she ages, events no longer happen in sequence. Her brain successfully remembers important things, but unlike you or I, the filing system is not chronological. Events in the past are classified as dreams, rather than "something I did yesterday afternoon."

She knows this is happening, and it frightens her - it would frighten anyone. My father was an engineer and when he noticed a diminished ability to remember, he stopped working on crossword puzzles. He was frightened he wouldn't remember.

Again--I'm the fun guy. With apologies to the family members who wrangle medications and bills and doctor visits, my job is to make Greta laugh. So when Greta is feeling blue, I put on my walking shoes and go to Stevens Point, Wisconsin for a visit. Sometimes for a week, usually longer. In this case, our stay was to be two months, possibly longer.

## **The Inciting Incident...**

The God I worship doesn't smite or crush or strike down mine enemies. But oh man--watch out for that omnipotent sense of humor. I'm certain God has a dashboard next to his almighty throne. The dashboard is covered in an infinite number of push-buttons. Each button has the name of one of his children.

When he deems it necessary, he speaks in a great voice, saying "I have called you by name, you are mine." This time, he pushes my button.

A display flashes the words "Banana Creme Pie Successfully Delivered!" Back here on Earth, these metaphysical pies-in-the-face manifest themselves in many ways. For some, it is a slip on a banana peel. For others, being chased by a rooster through a cow field. In my case I am hit with a lack of housing in Stevens Point.

## Plot Point One

Janell and I have tried to stay in Greta's room. Dimensions Living frowned upon this co-habitation and we chafed at the closeness of three of us 24 by 7 side by side. This is not a solution.

I investigated long-term residency at the neighboring Holiday Inn. \$3,000 per month. No free breakfast, but access to the pool, weight room, and as many towels as you want. That's a lot of moola for sleeping in the middle of the Clark County Fireman's Convention--or the FFA Regional Convention and Expo. Both events are loud and rowdy. Also not a solution.

I investigated AirBnB. There were no month-long stays available. I could string several one-week stays end-to-end. This too--not a solution.

We could purchase a house. We could then furnish the house. We could start gas, electric, water, sewer, and garbage service. Or we could hang out with Greta - but not both. Obviously not a solution.

We could rent an apartment. For a minimum of six months. In our dreams. Stevens Point has no available six month leases. Whether *we* were willing or not, this is also not a solution.

## **The Solution**

Janell and I are sitting in the lobby discussing our predicament when Jenna, the Director of Marketing for Dimensions Living joins us.

"I think I have something you'd be interested in hearing," Jenna says.

Janell and I perk up. Jenna is a source of local information with all the important contacts a Director of Marketing needs. She's friendly and we talk with her often. Maybe she's found a spare loft in the warehouse district. Maybe it has a floor and walls. Maybe it has vermin, but I know how to deal with those.

"We have a spare two-bedroom unit in the independent wing," she tells us. "It's not furnished, but comes with a meal plan. We can give it to you on a limited basis for the price of a single."

This means we would be within a two-minute walk of Greta's front door. And did I mention this is happening during Wisconsin winter? Any strategy to avoid going outside is looked upon favorably.

We discuss briefly, then realize this is our best (only) solution. We sign and are residents of Dimensions Living.

## Furnished Apartment

When Janell and I were first dating, I lived on a porch. In Minnesota. In winter. With no heat.

I did have a space heater. One of those gray, metal, 1,500-watt devices with the two chrome bars in the front, preventing fires if the unit ever tipped over on its face. It tried its best, but was no match for the lack of thermal conductivity from the panoramic view and wrap-around glass.

For a bed I had a two-inch foam pad and some sheets. Possibly a quilt. I was not big on home furnishings.

Janell was repelled by this sub-standard sleeping arrangement, but was attracted by my youthful exuberance. She stuck it out, but this was not to be repeated in our current situation. Once again, I realize how fortunate I was to marry her and put her in charge of improving my common sense.

Instead of a space heater and foam mattress, Janell's sister volunteers her furnishings currently in storage in a ULock facility in Milwaukee. We are free to use her bed, dressers and tables. All we have to do is move it from Milwaukee to Stevens Point and back again.

"No problem," I confidently assure Janell. "The CR-V has a tow hitch, we can rent a 6 x 12 trailer from U-Haul and we'll be set!"

All the enthusiasm, none of the experience.

The U-Haul dealer is willing to believe I know

[????? past tense present ??????????]{.underline}

what I was doing and even left me to attach the hitch by myself. I backed the CR-V up to the trailer then lifted the coupler onto the hitch ball. I tried. I lifted with my legs (not my back). Couldn't do it.

"hmmm...," I pondered to myself. Nobody else was around except the trailer and the CR-V. They weren't talking.

But the CR-V has a jack. Perfect. I jack up the coupler and trailer tongue, back the CR-V up, drop the jack, problem solved. The jack goes back in the car, I connect the safety chain, drive around the parking lot once to check my work, and everything is in tip-top shape. Let's go to Milwaukee!

There is a counseling device called Jahari's Window. It helps people understand their relationship with themselves and others. It is a grid of four squares: two rows, two columns. The columns are labeled "Know to self" and "Not known to self. The rows are labeled "Known to others" and "Not known to others." The cells in the grid occupy the intersection of row and column. Let's use this to examine my current situation.

**Known to others/Known to self:** I am driving to Milwaukee with a 6 x 12 trailer. This is not an unusual thing.

**Known to others/Not known to self:** Janell knows I should be less than confident. I am unaware of anything that could go wrong.

**Not known to others/Known to self:** I seem to be getting low on gas. And my goodness, it is starting to rain really hard.

**Not known to others/Not known to self:** I have neglected to tighten the coupler latch to the hitch ball.

Crusing down the highway at 65 mph (WARNING: DO NOT EXCEED 55 MPH WITH THIS TRAILER) I start to question my pre-flight checklist. Did I put on the safety chains? (yes). Did the trailer tires have air? (yes). Was the trailer empty? (yes). Did I tighten the coupler latch to the hitch ball? (Possibly not. Sure I did. Can't remember. Yes. No.) Perhaps I should check.

Ahead is a rest stop - perfect for checking coupler latches. I turn smoothly and begin to decelerate. Unfortunately, Wisconsin Department of Transportation has neglected their maintenance on this rest area. Potholes. BIG potholes filled with water. Potholes so frequent and so large they are impossible to dodge. I hit one, then a second. I look in the rear-view mirror and see the trailer lurching and bucking behind me. I feel a lurching tug; the trailer has clearly jumped off the ball and is now free to run me down or puncture my gas tank. I sloooowwwly come to a stop, trying not to irritate this 6x12 monster trailing my hapless CR-V.

I manage to stop and breathe. Everything is still on the road, the trailer is still behind me. I get out hoping for the best.

The trailer tongue is in the dirt. It has wedged itself under the car and come to the end of the chain. I don't smell gas and there aren't any unsightly bruises in the bumper. All I need to do is put the trailer back on the ball and we are good to go. So simple.

But the trailer is wedged under the car. I can't lift the car off the coupler. I lift with my legs. Can't do it. Like deja-vue, I remember the jack, which I use to lift the rear of the car, freeing the trailer.

Chock is a funny word. It's a noun, it's a wedge, and they come in sets of four. They are used to keep the wheels of cars or trailers from unexpectedly rolling. In a pinch, you can use a brick, or a stump, or a rock. I had neglected to chock the wheels on the trailer before lifting the car.

The newly freed trailer rolls backwards. I can only watch in dismay - I know enough to not step behind the trailer (empty weight: 1,920 pounds). Today, I am a lucky boy. The chains are still attached, the car is still in contact with the ground, the trailer reaches the end of its tether and stops with a jerk. I resume breathing.

This will be easy to solve. I disconnect the safety chains and pull the CR-V forward. I jack up the tongue of the trailer, then back the CR-V to the coupler. Only this time, I don't jack the trailer up far enough. I only nudge

## Room 202

This room is quiet, but not lonely.

To the east are sunny windows shining a pattern of light on a red chair. Miles Davis shares his genius of vibrating the air I breathe. One floor below me is a sidewalk where Tom and Pauline are walking Zero, their Norwich Terrier. Foxes (the furry kind with tails) live in the vacant lot to the southwest of the apartments next door. I've made coffee; I can get kitchen coffee from downstairs but mine is way stronger than they are willing to brew.

Janell is downstairs with Greta. They are participating in *drum fit*, an exercise class requiring a chair, drum sticks, and a stability ball. Jenny--from a video screen--calls out rhythms and demonstrates suggested application of sticks to ball. She's a blonde Taiko drummer, infusing her energy into the room filled with senior citizens of limited mobility and stability.

I'll join them at 11:30 am for lunch in the cafeteria. Today is beef tips on rice, green beans, a salad, roll, tapioca pudding, and beverage of choice. The kitchen serves me a large quantity because I'm the most active resident of Dimensions Living. Most everybody else gets the medium to small quantity. The kitchen staff quickly learns who needs extra salad and pudding and who leaves green beans and rice on their plate.

## Harassing The Natives

As a resident, I'm allowed to loiter in the hallways, and I frequently do so outside my mother-in-law's door. Her door is located on the main avenue between assisted living and the dining room, so there is a lot of foot traffic. To my left, I see Gladice approaching, pushing her walker.

I'm in a frivolous mood and like a construction-site hardhat at lunch, I call her out.

"Young lady," I bellow. "Do you have a hall pass? I think you should be in class, and if you don't have a pass, you'll have to report to the principal's office!"

Gladice is shorter than five feet, I'm taller than six. She has a curved spine and has to turn her head upwards to stare me in the eye.

"I think you can stick it in your..." Gladice pauses for a beat, then continues. "...ear. You can stick it in your ear!"

She was clearly considering a different orifice, but for the sake of decorum, she chose the safe option. I'm shocked, I say, SHOCKED to hear such a big thing come from such a small woman. We smile and she is on her way.

Later, she stops by to ask forgiveness for her spicy response. Janell steps in, "Gladice, you said exactly the right thing. You're my new best friend." I'm being ganged up on by the women - deservedly so.

## 

------------------------------------------------------------------------

## **3. The middle event**

The middle event should occur (you guessed it) about 50 percent of the way through your story.

Up until this point, your protagonist has been making reactive decisions based on the events of the plot. This is because everything that's happened to them after the inciting incident is new and unfamiliar terrain.

The purpose of the middle event is to force your protagonist to stop reacting to events as they happen. After this, they actively influence plot events by instigating the action in the second half of the story.

How do you shift the protagonist from reactive to active?

You could make something unexpected, terrible, or life-changing happen to your protagonist. Whatever it is, they have to find the strength to deal with this event and finally take the reins.

Examples of a middle event:

-   If your protagonist doesn't pass the mid-year exams at the magical academy, they'll be expelled, and will have to actively study hard to keep their place.

-   The bad guys kidnap your detective's daughter, and they'll have to actively work hard to get her back.

-   A close friend warns your protagonist if they don't change their ways, they'll always be alone, and they have to actively work to keep their relationship going.

## **4. Plot point two**

Plot point two (which should occur around the 75 percent mark of your story) is your protagonist's lowest moment.

Although they've been active in influencing the plot since the middle event, every action they've taken has made things worse and worse until... the protagonist reaches their lowest moment. And that's exactly what Plot point two is: the worst moment for your protagonist so far.

Other names for plot point two include:

-   The tragedy

-   Hitting rock bottom

-   The dark night of the soul

Something happens that puts everything the protagonist has done to work towards their story goal at risk, and they're in danger of losing everything.

Examples of a plot point two:

-   Your protagonist's magical mentor dies.

-   The protagonist detective gets taken off the case.

-   Your protagonist's love interest says they need to take a break from their relationship.

## **5. The climax**

You've built your story up to the climax with rising action, and now the climactic scene (or scenes) will have the highest level of conflict, the greatest tension, and/or the most devastating emotional upheaval.

Several things vital to your climax include:

-   Your protagonist needs to be in the scene(s).

-   Your protagonist needs to resolve the conflict (no other character can do this).

-   The conflict and tension need to be highest at this point in the story.

-   You need to avoid deus ex machina (an unexpected power or event resolving the conflict, rather than your protagonist).

-   The central conflict of the story must be resolved.

The protagonist should face the biggest obstacle in the story and determine their own fate.

## 
