# Aging {.unnumbered}

I've been twenty-five for about four decades. This month, I awoke to find I'm suddenly sixty-five. I use adverbs sparingly, but in this case, "suddenly" fits.

Physical activity is more difficult.

When I was twenty-five, I could run a five-minute mile. I flipped a canoe on my shoulders, then down, then up again sixteen times in thirty seconds. I could carry a two-hundred and fifty pound load up a sand dune.

Now my back hurts when I get out of bed in the morning.

Mentally, I'm slower. When I was twenty-five, I played bass guitar in a rock-and-roll band. I learned music theory. I picked up the banjo and taught myself to sight-read.

Now I can't remember where I put my keys.

To document my *sudden* aging, the United States government sends me paperwork about enrolling in social security and medicare. I read it and laugh about how that is for old people. I stop laughing when I realize I'm the *old people* they are talking about.

I have grandchildren. My hair (and beard) is white. My skin is thinner, my knees complain when I stand up. Industry head-hunters have stopped calling me with job offers. In five years, I'll be seventy.

I have finally gained a fine patina of wisdom. When I was twenty-five, I strove to be respected by my peers. I read management books and attended workshops on effective leaders and time management and the latest bullshit theory of the month. I find out that patina is easy to come by, it's called "liver spots."

This is the first time I've gotten old and I am totally unprepared for the changes happening and the changes I'm required to make in myself. I was hoping the literature accompanying the medicare and social security paperwork would offer a seminar (hopefully in some exotic location) about how to age gracefully. There are such seminars, but they are taught by forty-year-old celebrities and are mainly concerned about choosing make-up and fashion. Nothing about how an old white male is supposed to proceed with confidence. Of course, old white males have never lacked for an undeserved sense of confidence, so why start worrying now?

I realize I should observe someone older than myself. If I paid careful attention, I could see their triumphs and their failures. I could take careful notes and optimize my own experience. I need a mentor to show me how to get older.

Fortunate me, I realize I have a perfect mentor and I'm related to her.

My Favorite-Mother-In-Law!
