---
title: "obituary"
format: html
editor: visual
---

# **Greta Ross**

## December 10, 1934 — July 2, 2024

Greta Marie Ross, 89, Stevens Point, Wisconsin

Greta Marie Ross, mother, grandmother, and friend, passed away on July 2nd, 2024, at 89 years of age. Greta was born on December 10, 1934, to Henry and Esther Gebert, in the township of Holton, Marathon County, three miles north of Dorchester, Wisconsin. She was baptized at St. Louis Catholic Church on January 6, 1935.

Greta grew up in a loving family, helping in the house and on the farm. Her father affectionately called her "Gretz," and in later years spent many evenings together at Henie's Place, where she often helped tend bar. Greta admired her mother, Esther, who sent her to Medford to pick out the latest songs for the tavern's jukebox, like Patsy Cline, Hank Williams, and Gene Autry, sparking a lifelong love of music, including grade school operettas, and playing piano. She told of often sitting up till midnight on Saturday to listen to The Grand Ole Opry. She had a close-knit family, with siblings Lucille, Jeannette, Clarence, Raymond, and Luanne.

Greta graduated from Dorchester High School and then earned her Teacher Training diploma in 1954 from Taylor County Normal School. She began her teaching career at Wild Rose and Crie one-room schools, where she instilled a love of learning in her students. Greta was especially proud of the autumn and Christmas programs with her students, showcasing her gentle discipline and creative approach to education. Her harshest discipline was telling one rambunctious little girl she should sit down!

On July 25, 1956, Greta married Eugene Ross, the love of her life. Together, they moved to Neillsville, Wisconsin, where they raised their five children; Gary, Janell, Connie, Robert, and Kathleen, in a warm and loving home.

Greta was an active and devoted member of St. Mary's Catholic Church in Neillsville. She sang in the choir, taught catechism classes, and prepared meals, cakes, and pastries for funerals and church functions. Her faith was a cornerstone of her life and she regularly attended daily Mass. Greta also had many dear friends in Neillsville and enjoyed taking part in bridge and cribbage groups, as well as traveling with her friends.

After Gene's passing, Greta found solace and purpose in volunteering at The High Grounds Veterans Memorial Park and working at a local shoe store. She moved to Dimensions Living Assisted Care in Stevens Point in 2020, where she continued to spread her warmth and kindness.

As a homemaker, Greta was exceptional. Her house was always spotless and her meals were delicious and wholesome, with many vegetables coming from her own garden. She canned and froze many quarts of fruits and vegetables for the winter. She delighted in teaching her grandchildren many things, like how to crack eggs and make cinnamon rolls, cutting the rolled up dough with a piece of thread. Greta also loved her 50+ nieces and nephews, always welcoming visitors with a meal and fresh homemade goodies.She leaves behind a legacy of love, kindness, and faith.

The Mass of Christian burial for Greta is scheduled for July 8th, 2024, at 11:00 am at St. Mary's Catholic Church, Neillsville. Visitation will be from 9:00-10:45 am in the church narthex.

Following Mass and final service at the cemetery, please join the family for a luncheon in the church hall.

Surviving: brother-in-law, Pete Wanke of Medford, WI, Children; Gary (Rose) Ross of Custer, WI, Janell (Mark) Niemann-Ross of Portland, OR, Connie Ross (nee Schwartz) of Lakewood, CO, Robert (Lisa) Ross of Appleton, WI, Kathleen (Michael) Rusovick of Westminster, CO.

Grandchildren: Will (Stephanie), Henry (Lisa), Benjamin (Lindsey), Aaron, Phillip (Lacey), Alexander, Garrett (Marisol), Abigail, Tatum (Daniel), Katherine, Samuel, Claire, Olivia (Elijah), Matthew, Juliana, Jacob

Great grandchildren: Noah, Miles, Lindy, Finnley, Everly, Maverick, Ransom, Montana, Ella, Joseph, Colette, Theodore.

Preceding her in death are her parents, Henry and Esther Gebert, husband Eugene, infant daughters Mary and Maryann, her siblings Lucille (Herman) Sebold, Jeannette (John) Robida, Clarence (Betty) Gebert, Raymond (Helen) Gebert, Luanne Wanke, and Son-in-law Dean Schwartz.

In lieu of flowers memorials may be made to: The HighGround Veteran’s Memorial Park, [http://campaign.thehighground.us](http://campaign.thehighground.us/) or St. Mary's Catholic Church music program, 1813 Black River Road, Neillsville WI 54456.

We wish to thank the staff at Dimensions Living and interim Hospice for their compassionate and loving care of Greta, and Fr. Mark Miller for his pastoral care, especially in her final days.

Online Condolences may be made at www.geschefh.com.

Gesche Funeral Home and Cremation Service is assisting Greta's family with Funeral arrangements.

In Greta's own words, "I loved my life and I wouldn't change a thing if I could live it again."

*Know that I could listen to your voice for hours on end*

*and still mistake it for music.*

*\~ Claire Amara Rusovick, granddaughter*
