# Tech Support {.unnumbered}

I'm hanging out with Greta, my mother-in-law, at her apartment in the memory care unit of Dimensions Senior Living. I'm reading to her when my phone rings.

It's from area code 503 - a long distance call from my home state of Oregon. I don't recognize the number, so I suspect a spammer. But, Greta and I could use a laugh so I answer and put the call on speaker phone.

"Hello. This is Thomas from Microsoft Technical Support." Thomas has a distinct accent and I can hear voices in the background. "Your computer is sending many virus to the internet and I am calling to help you clean the virus off your computer."

Greta is alarmed to hear this, but only because she has forgotten she doesn't have a computer. This may be a bit beyond what she will find humorous, but I'm interested.

"Perfect," I reply. "We've been having some problems with Facetime and I was hoping someone from Microsoft would be available to help."

You may know Facetime is an Apple product--not Microsoft. I am deliberately misleading Thomas, but this mismatch doesn't seem to be a concern.

"That is good," replies Thomas. "Are you sitting in front of the computer?"

Game on.

## Greta By Wire

Let's put Thomas on hold for just a minute. Before we go any further, I must confess that I *spy* on Greta.

I receive reports from the staff on her attendance at activities throughout the week. I watch her interact with her peers at breakfast, lunch, and dinner. I am a helicopter son-in-law.

I spy on Greta because I want the best for her. I want to encourage her to go to Drumfit exercise class. I want her to go to mass. I want her to engage with the world and not just sit alone in her room. She's happier when she's interacting and I assume an active mind is a healthy mind.

If I wanted to, I could intensify my surveillance. My day gig is programming single-board computers with the python programming language. I post videos on how to build a weather station or implement telemetry transport between two microprocessors. I have an in-depth knowledge of the technologies necessary to place a camera in Greta's room and record her every motion.

I could also build a two-way wrist-radio for Greta. We could talk like Dick Tracy. I would know exactly where she was, updated every 500 milliseconds.

But this would be neither respectful, necessary, or realistic.

## The Promise

Of course, I don't need to build my own surveillance device. There are many pre-built devices for elders and their children to stay in touch. Some of them allow children to monitor their parents; a reverse nanny-cam. Promotional websites and videos show happy senior citizens happily interacting with their grandchildren over a flawless video link. Everyone has perfect make-up and interesting dialog.

In fact, Greta's children have purchased an internet-connected picture frame. We send photos of our lives over the internet. They fly to her picture frame where they are displayed in a continuous loop near her favorite chair. She doesn't need to do anything to watch the pictures change, and they show her children camping, her grandchildren swimming, or someone's new house. It's the electronic equivalent of the paper photo albums in her room.

## The Reality

I made my fortune in high-technology and approach new technology with enthusiasm and optimism. I've worked on projects that have changed society and industry. I look with admiration at the emergence of new technologies and the thrill of the youngsters introducing this new round of world-changers.

However, I've become a skeptic. Simply--the creators of these devices are clueless about what it takes to bring Greta closer to her family.

## Reading to Greta

When I'm in Stevens Point, I'm with Greta most of the day, reading. She has macular degeneration so her eyesight isn't good. She loves to be read to, so we spend a lot of time side-by-side on the couch, me reading, her listening. One of her favorites is a book of poetry written by one of her grand-daughters, Claire Amara. Claire writes about love and anguish, Greta listens to a poem, then remarks how wonderful it is.

"How does she know this?" Greta remarks. "That is so very thoughtful."

"I don't know," I respond. I've tried to get Claire to read her poems to Greta, but Claire won't do it. I understand---these poems come from deep inside her life. But I wish I had better insight so I could share this moment of lucidity with Greta.

Tomorrow, I will read the same book of poems to Greta, and she will say much the same things with the same sense of wonder. I'm saddened because Greta doesn't have the brain chemistry necessary to carry these poems with her, but envious of her constant sense of amazement and appreciation. She never takes Claire's poetry for granted.

## Greta's Memory Versus Greta's Pictures

When we are done reading Claire's book, I pick up the internet-connected picture frame. Like Claire's poetry, I interpret each image for Greta.

"This is your great-granddaughter. She is playing in the water with her mother. This was about a month ago when we were at the family reunion at Green Lake. You were there."

"Oh," Greta responds. "I don't remember that. I was there? Who is this little girl?"

"That is your great-granddaughter," I respond. "We were at the family reunion at Green Lake." I pause for a minute, then swipe left to the next image.

"This is your grandson at his new business," I'm actually not sure what we are looking at, but her grandson is in the picture. I'm improvising.

"Oh. Now, which grandson is this?" Greta is working hard to keep her family tree intact, but the branches shift in the wind.

"It's your second daughter's first son," I prod her memory. "He's a successful entrepreneur." I guide her through these memories. If I invoke the right triggers, she will remember. But this time, her brain stubbornly refuses to make the connection. I move on to the next image.

When Greta tires, or is called for a meal, she will forget these images until the next time we sit on the couch. I will narrate these images and the smiling people they contain. She won't pick this device up on her own - the pictures are meaningless without someone providing context and insight. By itself, this wondrous picture frame is no more significant than the clock on the wall.

*Oh my gosh*--I've almost forgotten Thomas from Microsoft Technical Support. I click the hold button and bring him back on speaker phone.

"Thomas, are you still there?" I hold the phone up in my right hand so Greta can see. It helps her attention to visualize what she is hearing. In my left hand is the picture frame. "Greta and I were just getting her computer. We're looking at pictures!"

"That is good," Thomas replies. "Whom am I speaking with?"

"I apologize," I say. "I'm Mark and next to me is Greta. She is my favorite mother-in-law."

There is a moment of silence on the phone. "Do you have more than one mother-in-law?" asks Thomas.

"No. She is my only mother-in-law. But she is my favorite." Greta and I chuckle at the inside joke. "Can I ask you a question about this computer?"

"Um. Sure," replies Thomas. "First, I need you to..."

"Why doesn't this computer have a battery?" I interrupt Thomas mid-phrase and I gesture at the internet picture frame. It is a computer, after all. "Do you have any idea how inconvenient it is to sit on the couch when the power outlet is further than the power cord can reach? It would be so much better if I could unplug it while we were looking at it!"

"Is the computer on right now?" Thomas asks. He sounds puzzled.

"Well yes, of course. How else would we be able to watch pictures? But I've had to steal the extension cord from the lamp. It's a good thing it's the middle of the day and we are sitting next to the window or we wouldn't be able to see anything."

"By the way," I continue without giving Thomas the courtesy of a conversational opening. "Did you know I write Science Fiction?"

"Like Isaac Asimov?" says Thomas. "I love Asimov."

## Telepresence with Greta

Thomas is relating his reading list and will be busy for a while. We can ignore him for a minute as I stray into my first love of science fiction. Wouldn't it be wonderful If I could travel from Portland to Greta's room without the burden of traveling for five days?

*POP* - I'm in Stevens Point. "Hello Greta," I would say, shaking the time-travel residue from my shoes.

"Oh, hello Mark," She would respond without surprise. Time and space travel means nothing to someone who experiences discontinuity of time and space. All Greta cares about is that I am here.

This is the promise of these senior-friendly video communicators. Turn on the video connection and *POP.* I am here! Let's interact!

But these devices fall short of their promise. Unlike my effortless time/space travel, they require a series of steps.

1.  Turn the device on.

2.  Start the communication app

3.  Look at the camera and talk

4.  Disconnect the conversation when done

5.  Put the device away

And even then, it's not me. There's no contact. I'm not sitting on the couch.

Let me break this down into smaller chunks.

### Turn the device on/start the app/look at the camera

These first steps assume several things. First, Greta and grandchild/child have an agreement about *when* to turn the device on. You would think she is available at all times every day, however:

-   If it is mealtime, Greta will be in the dining hall and not available.

-   If Greta has a medical appointment, she won't be in the building.

-   If she is at *Drumfit*, she won't be in her room.

-   If she is sleeping, nobody will wake her.

-   If she is having a bad day, her attendant may not have the patience to get her in front of the camera.

Let's assume the best set of circumstances; Greta is in the room, awake, and an aide is nearby. The device issues an audible alert which the aide understands is a request to start a conference between Greta and an interested party.

The aide picks up the device. Is the app visible? Is there a button that is clearly labeled "talk to *someone*." The aide helps Greta move to a place where she can see the device.

Great. Greta is sitting at the table in front of the device. Greta (and most people I know) don't instinctively look at the camera on the device. They look at the image of the person calling them. So on our side of the conversation, we see the inside of Greta's nose or the top of her forehead.

If I wasn't here to mediate between Thomas and Greta, his efforts to defraud her would be completely wasted. Assuming her aide was willing to make the connection in the first place, Thomas would only see a portion of her face and they would never get to the point where he could show her the virus infecting her computer and sending spam to her friends.

### Disconnect the conversation when done

Let's assume the best of all outcomes and thus, Greta has a conversation with child or grandchild (or Thomas). The child overcomes their need to see Greta's face and accepts her forehead as a reasonable alternative. They find something to talk about. The conversation is over and everyone says their goodbyes.

This is ignorant of Greta and her emerging chronological discontinuity. Remember; Greta perceives time in shorter loops than you or I. *Yesterday*, *this morning, today,* and *tomorrow* are no longer clearly defined. Those of us who are firmly rooted in linear time assume a conversation has a salutation, a body, and a close. Greta does not.

When I am in Greta's physical presence, I know a conversation will last until she needs a nap or dinner starts or the nurse arrives to check blood pressure or another interruption. It's not when I have completed a logical discussion of the topic for today. The queues to the stage of a conversation aren't available via video link.

### Put the device away

For the sake of a continued dissertation, let's assume the conversation has somehow ended. Our distant person logs off. Greta is left with a mute device (and probably an aide). Time to put the device away.

An aide will assume the device is fine where it is. Greta will assume the device has ceased to have importance and will leave it where it is. Or she will put it in a safe place.

Janell and I have established a secret message. I will say something like "Janell, I put \[*a thing*\] in a safe place."

Janell understands the phrase "safe place" as "I can't remember where I put it." The thing is lost until I trip over it or discover it in the refrigerator or other logical storage area.

So when I say Greta will put the device in a safe place, I mean she will lose it.

We (the royal *we)* would also like to believe the device is connected to power so it can recharge. More likely, the device is left unplugged on a table or near an armchair. At first, it is on the top of the stack of papers, but it is soon covered with *Catholicism Today, Wisconsin Travel*, The local *Pennysaver,* and a birth/wedding announcement from a grandchild. Hopefully it does make an audio alert so an aide can locate it under the stack. It's just as likely someone from house cleaning or a child-in-charge will place the growing stack of paper in recycling without realizing the stack contains a mute device.

Some devices have a "find me" feature which allows a smart phone to return the physical location or to play a loud signal. All these assume the device is charged, which implies it was plugged in the last time it was used. Both are unlikely.

## The Upside

"Mark? Greta?" Thomas interrupts the narrative. "Can we resume working on your virus?"

"Sorry Thomas, I was pontificating," I admit. "Do you mind if I conference in Greta's granddaughter Abby?"

"Does she have a computer?" asks Thomas.

"Hopefully. She lives in London," I say. "She does Facetime. Hang on a second."

Without waiting for Thomas's consent, I put him on hold and dial London. Wonder of wonders, Abby appears.

On a side note, I will point out this morning I found the iPad on the shelf under the statue of the Madonna. I plugged it in for a charge. I also checked the time from Wisconsin to London to make sure the call is reasonable for both continents. I also know Apple Facetime is the communication app of choice (not hangouts or zoom or skype. Remember skype?)

I bring Thomas back and now it is a three-continent phone call.

"Thomas, please meet Abby. Thomas is from Microsoft Technical Support and is going to help us fix a virus. Greta is here with me."

"Uncle Mark," says Abby. "Is Thomas someone you know? He's probably a spammer!"

"Of course he's not a spammer," I say. "Thomas and I have a shared love of science fiction. Thomas, tell Abby you're not a spammer."

Thomas hasn't turned on his video and is silent. I can see he's still connected but has become non-participative.

"Well, Thomas must be having some connection difficulties," I apologize on Thomas's behalf. "Abby - Greta would like to hear all about London!"

"Hello Abby," says Greta. "You look happy!"

## No Way Around It

I was thinking how I might engage Thomas to make a periodic video call to Greta. I suspect they would have many things to talk about. But video calls really aren't what Greta needs and I suspect Thomas's time zone would be from somewhere other than the 503 area code.

These wondrous devices are like hand puppets; they have no more value than the person holding them. Without a performer and an audience, they are just inert lumps of silicon and plastic. Greta depends on me to be there to animate the puppets, they just don't work by remote control.

I read to my kids, I read to my students, and I read to Greta. My best times reading are in person, one-on-one, side-by-side on the couch. It's something I have a limited amount of time to do. Why would I want to do it anywhere else?
