# Sundowning {.unnumbered}

We first met Greta's evil twin after we left the wedding of one of the grandsons.

It had been a long and festive event, attended by the entire Ross clan. There are more of them than there are of me. They all know who I am and they take perverse delight in asking trivia questions about their family history. I should have commissioned flash cards and had Janell drill me on names, birthdays, city of residence, five pertinent facts of each uncle and aunt. At the least I should have practiced drawing the Ross family tree on poster board.

I have a cousin who excels at this game of *Hūsker Dū?* He will tell you about the party you were at when someone dropped a cake on the picnic table. I will have no recollection of the picnic, nor being at the picnic, nor dropping the cake. At this point, he could tell me any outlandish lie and I would believe it because he has never been wrong.

This grandson's wedding was a massive Ross reunion (as are they all) and I was exhausted. I suspect Janell and Greta were as well. We had rented a hotel room nearby, planned to get some sleep, then drive home the following day. Greta was in the back seat, Janell and I in front.

"I cannot believe I have such ungrateful children," Greta suddenly speaks up in the dark. "I am going to give all of my money to charity and you will get none of it."

This was *not* spoken in a teasing voice. Greta was serious and angry. Greta's norm is happy and tolerant, loving and expansive. This was Evil Greta. Who the hell is in the back seat and how am I supposed to react? Know that I am conflict-avoidant and this was shaping up to be one large conflict. I was happy to be driving.

There *had* been an incident at the wedding. One of Greta's children felt it was appropriate to proselytize to one of the grandchildren and girlfriend. His words were unwelcome and caused tears, leaving the rest of us to mitigate this emotional exchange. Greta may have heard some of the discussion. That's what I assumed this was about. But Greta wouldn't say what was bothering her, only that she was disgusted with us.

Janell and I had no idea where this Greta came from. Looking back, there were clues, but we didn't know to look for them. At the hotel, she wanted me to get her suitcase out of the car--I had seen her place it in the closet just five minutes before. She asked twice why we were staying in this strange room.

She was angry and sullen until the following morning when we joined some of the grandkids for breakfast. Over waffles, bacon, and coffee she perked up and we were again in good graces. Evil Greta was gone.

In the next months and years, Evil Greta periodically reappeared. We would receive nasty emails and phone calls. The next morning she would be chipper and friendly. She had no recollection of sending us an email with ALL CAPS ABOUT THE LATEST EVILS IN THE MODERN WORLD!!!!!

In time, we learned this is called *sundowning*. It is an early indicator of dementia, often associated with Alzheimer's disease. Over a short period of time, she became confused with how to operate email and the nastygrams ceased.
