# Twenty-Four By Seven {.unnumbered}

Greta didn't thrive at Dimensions Living. She was upset she had to leave her home and live with all these *old* people. Her health declined and she transferred to medical care, then recovered enough to move to rehab. At rehab she declined and entered hospice care. Janell flew out to be with her.

Here's the catch. If you need 24x7 care, you can't move back to Dimensions Living. They don't have the license or personnel required to provide that level of support. But you can't remain housed at the rehab facility forever, insurance only pays for a limited time. Greta would have to find a new place to live out her days and her options were few.

Here's the loophole. *If the siblings hired 24x7 care for Greta then she could return to Dimensions*. But damn, that's expensive!

There are a few details I haven't mentioned just yet;

Janell retired a few months previous.

Janell has a medical degree.

I have a job which doesn't require I be in any particular place at any time.

What to do.

What to do?
